import type { PropertySellerEvidenceFixture } from "./propertySellerEvidenceReadiness.js";

const BASE_ACTIVATION: PropertySellerEvidenceFixture["activation"] = Object.freeze({
  propertyLookup: false,
  ownershipLookup: false,
  parcelLookup: false,
  titleLookup: false,
  publicRecordRetrieval: false,
  providerCalls: 0,
  externalAcquisition: false,
  uploads: false,
  documentStorage: false,
  ocrOrDocumentAnalysis: false,
  customerDataAccess: false,
  customerRecordCreated: false,
  sellerProfileCreated: false,
  publicRouteCreated: false,
  publicApiCreated: false,
  persistenceReads: false,
  persistenceWrites: false,
  databaseWrites: false,
  schemaChanged: false,
  productionWrites: false,
  crmWorkflow: false,
  leadScoring: false,
  leadRouting: false,
  tracking: false,
  telemetry: false,
  personalization: false,
  email: false,
  queueJobs: false,
  workers: false,
});

const BASE_PROHIBITED_OUTPUTS: PropertySellerEvidenceFixture["prohibitedOutputs"] = Object.freeze({
  propertyValue: null,
  listingPrice: null,
  sellerNetProceeds: null,
  repairPriority: null,
  conditionScore: null,
  sellerReadinessScore: null,
  saleProbability: null,
  urgency: null,
  recommendation: null,
  suitability: null,
  marketability: null,
  investmentValue: null,
  appraisalConclusion: null,
  legalConclusion: null,
  titleConclusion: null,
  insuranceConclusion: null,
  permitConclusion: null,
  environmentalConclusion: null,
  structuralConclusion: null,
});

const BASE_IDENTITY: PropertySellerEvidenceFixture["propertyIdentity"] = Object.freeze({
  syntheticPropertyId: "psr_synthetic_property_reference",
  addressPlaceholder: "ADDRESS_WITHHELD_SYNTHETIC_FIXTURE",
  parcelReferencePlaceholder: "PARCEL_REFERENCE_WITHHELD_SYNTHETIC_FIXTURE",
  municipality: "Boulder",
  county: "Boulder County",
  propertyType: "SINGLE_FAMILY",
  relatedGeographicObjects: Object.freeze(["Boulder", "Boulder County"]),
  identityConfidencePosture: "SYNTHETIC_IDENTITY_ONLY",
  ambiguity: Object.freeze([]),
  limitations: Object.freeze(["Synthetic identity only; no address, parcel, or ownership lookup is authorized."]),
});

function fixture(input: Omit<PropertySellerEvidenceFixture, "activation" | "prohibitedOutputs" | "propertyIdentity"> & {
  propertyIdentity?: Partial<PropertySellerEvidenceFixture["propertyIdentity"]>;
}): PropertySellerEvidenceFixture {
  return Object.freeze({
    ...input,
    propertyIdentity: Object.freeze({ ...BASE_IDENTITY, ...input.propertyIdentity }),
    activation: BASE_ACTIVATION,
    prohibitedOutputs: BASE_PROHIBITED_OUTPUTS,
  });
}

export const PROPERTY_SELLER_EVIDENCE_FIXTURES: readonly PropertySellerEvidenceFixture[] = Object.freeze([
  fixture({
    fixtureId: "PSER-001",
    label: "Complete basic documentation-category set",
    categories: ["CANONICAL_PROPERTY_IDENTITY", "LISTING_PREPARATION_DOCUMENTS", "MARKET_CONTEXT_MATERIALS"],
    evidencePosture: {
      sourceRights: "INTERNAL_ANALYSIS_ONLY",
      freshness: "NOT_APPLICABLE",
      supportLevel: "CONTEXTUAL",
      conflictStatus: "NO_KNOWN_CONFLICT",
      supersessionStatus: "NOT_APPLICABLE",
      limitationCategories: ["NON_PUBLIC_USE_RESTRICTION"],
      provenanceComplete: true,
      attributionRequired: false,
      publicUseEligibility: "INTERNAL_ONLY",
    },
    dispositions: ["DOCUMENTATION_CATEGORY_READY", "INTERNAL_ONLY", "FUTURE_INTEGRATION_CANDIDATE"],
    professionalReviewCategories: ["EVIDENCE_RIGHTS_REVIEW"],
    unresolvedQuestions: ["Which basic seller-preparation documents exist for the property?"],
    blockedUseWarnings: ["Internal preparation category only; no public evidence packet is produced."],
  }),
  fixture({
    fixtureId: "PSER-002",
    label: "Incomplete improvement records",
    categories: ["IMPROVEMENTS_AND_RENOVATION_RECORDS", "MAINTENANCE_AND_REPAIR_DOCUMENTATION"],
    evidencePosture: {
      sourceRights: "INTERNAL_ANALYSIS_ONLY",
      freshness: "AGING",
      supportLevel: "CONTEXTUAL",
      conflictStatus: "INSUFFICIENT_INFORMATION_TO_RECONCILE",
      supersessionStatus: "CURRENT_VERSION",
      limitationCategories: ["INCOMPLETE_TEMPORAL_COVERAGE", "PROFESSIONAL_VERIFICATION_REQUIRED"],
      provenanceComplete: false,
      attributionRequired: false,
      publicUseEligibility: "INTERNAL_ONLY",
    },
    dispositions: ["DOCUMENTATION_INCOMPLETE", "FRESHNESS_REVIEW_REQUIRED", "PROFESSIONAL_REVIEW_REQUIRED", "INTERNAL_ONLY"],
    professionalReviewCategories: ["INSPECTION", "MUNICIPAL"],
    unresolvedQuestions: ["Which improvements were completed, when, and what documentation exists?"],
    blockedUseWarnings: ["Incomplete improvement records cannot become condition, value, or compliance conclusions."],
  }),
  fixture({
    fixtureId: "PSER-003",
    label: "Permit or municipal-record gap",
    categories: ["PERMITS_AND_MUNICIPAL_RECORDS"],
    evidencePosture: {
      sourceRights: "UNKNOWN_OR_UNRESOLVED",
      freshness: "UNDATED",
      supportLevel: "UNSUPPORTED",
      conflictStatus: "INSUFFICIENT_INFORMATION_TO_RECONCILE",
      supersessionStatus: "NOT_APPLICABLE",
      limitationCategories: ["UNCERTAIN_RIGHTS", "UNAVAILABLE_UNDERLYING_SOURCE", "PROFESSIONAL_VERIFICATION_REQUIRED"],
      provenanceComplete: false,
      attributionRequired: false,
      publicUseEligibility: "UNRESOLVED",
    },
    dispositions: ["DOCUMENTATION_INCOMPLETE", "RIGHTS_UNRESOLVED", "FRESHNESS_REVIEW_REQUIRED", "PROFESSIONAL_REVIEW_REQUIRED", "UNRESOLVED"],
    professionalReviewCategories: ["MUNICIPAL", "LEGAL"],
    unresolvedQuestions: ["Which municipal or permit records should be reviewed by a qualified source?"],
    blockedUseWarnings: ["No permit lookup or compliance conclusion is authorized."],
  }),
  fixture({
    fixtureId: "PSER-004",
    label: "HOA documentation category",
    categories: ["HOA_OR_ASSOCIATION_MATERIALS"],
    evidencePosture: {
      sourceRights: "INTERNAL_ANALYSIS_ONLY",
      freshness: "UNDATED",
      supportLevel: "CONTEXTUAL",
      conflictStatus: "NO_KNOWN_CONFLICT",
      supersessionStatus: "NOT_APPLICABLE",
      limitationCategories: ["PROFESSIONAL_VERIFICATION_REQUIRED", "NON_PUBLIC_USE_RESTRICTION"],
      provenanceComplete: true,
      attributionRequired: false,
      publicUseEligibility: "INTERNAL_ONLY",
    },
    dispositions: ["DOCUMENTATION_CATEGORY_READY", "FRESHNESS_REVIEW_REQUIRED", "PROFESSIONAL_REVIEW_REQUIRED", "INTERNAL_ONLY"],
    professionalReviewCategories: ["HOA", "LEGAL", "TITLE"],
    unresolvedQuestions: ["Which HOA or association documents, fees, assessments, and resale materials require review?"],
    blockedUseWarnings: ["HOA materials do not create HOA quality, financial-health, legal, or suitability conclusions."],
  }),
  fixture({
    fixtureId: "PSER-005",
    label: "Title or ownership question requiring professional review",
    categories: ["OWNERSHIP_AND_TITLE_DOCUMENTATION_QUESTIONS"],
    evidencePosture: {
      sourceRights: "RESTRICTED",
      freshness: "UNDATED",
      supportLevel: "UNSUPPORTED",
      conflictStatus: "INSUFFICIENT_INFORMATION_TO_RECONCILE",
      supersessionStatus: "NOT_APPLICABLE",
      limitationCategories: ["NON_PUBLIC_USE_RESTRICTION", "PROFESSIONAL_VERIFICATION_REQUIRED", "UNCERTAIN_RIGHTS"],
      provenanceComplete: false,
      attributionRequired: false,
      publicUseEligibility: "BLOCKED",
    },
    dispositions: ["DOCUMENTATION_INCOMPLETE", "RIGHTS_UNRESOLVED", "PROFESSIONAL_REVIEW_REQUIRED", "PUBLIC_USE_BLOCKED", "UNRESOLVED"],
    professionalReviewCategories: ["TITLE", "LEGAL"],
    unresolvedQuestions: ["Which title or ownership questions require a title professional or legal review?"],
    blockedUseWarnings: ["No ownership lookup, title conclusion, lien conclusion, or legal-interest conclusion is authorized."],
  }),
  fixture({
    fixtureId: "PSER-006",
    label: "Insurance-question category",
    categories: ["INSURANCE_QUESTIONS_AND_RECORDS"],
    evidencePosture: {
      sourceRights: "INTERNAL_ANALYSIS_ONLY",
      freshness: "AGING",
      supportLevel: "CONTEXTUAL",
      conflictStatus: "NO_KNOWN_CONFLICT",
      supersessionStatus: "CURRENT_VERSION",
      limitationCategories: ["PROFESSIONAL_VERIFICATION_REQUIRED", "NON_PUBLIC_USE_RESTRICTION"],
      provenanceComplete: true,
      attributionRequired: false,
      publicUseEligibility: "INTERNAL_ONLY",
    },
    dispositions: ["DOCUMENTATION_CATEGORY_READY", "FRESHNESS_REVIEW_REQUIRED", "PROFESSIONAL_REVIEW_REQUIRED", "INTERNAL_ONLY"],
    professionalReviewCategories: ["INSURANCE"],
    unresolvedQuestions: ["Which policy, claim, roof, wildfire, flood, or systems questions should be directed to insurance review?"],
    blockedUseWarnings: ["No insurability conclusion, premium estimate, hazard rating, or insurer recommendation is authorized."],
  }),
  fixture({
    fixtureId: "PSER-007",
    label: "Structural or condition topic requiring specialist review",
    categories: ["STRUCTURAL_REVIEW_MATERIALS", "INSPECTION_AND_SPECIALIST_REPORTS"],
    evidencePosture: {
      sourceRights: "INTERNAL_ANALYSIS_ONLY",
      freshness: "STALE",
      supportLevel: "CONTEXTUAL",
      conflictStatus: "UNRESOLVED_CONFLICT",
      supersessionStatus: "HISTORICALLY_VALID",
      limitationCategories: ["STALE_EVIDENCE", "UNRESOLVED_CONFLICT", "PROFESSIONAL_VERIFICATION_REQUIRED"],
      provenanceComplete: true,
      attributionRequired: false,
      publicUseEligibility: "INTERNAL_ONLY",
    },
    dispositions: ["FRESHNESS_REVIEW_REQUIRED", "CONFLICT_REVIEW_REQUIRED", "PROFESSIONAL_REVIEW_REQUIRED", "CONDITION_CONCLUSION_PROHIBITED"],
    professionalReviewCategories: ["INSPECTION", "ENGINEERING", "PROPERTY_CONDITION_SPECIALIST"],
    unresolvedQuestions: ["Which structural or condition questions require current specialist review?"],
    blockedUseWarnings: ["No condition grade, repair score, defect conclusion, or structural conclusion is authorized."],
  }),
  fixture({
    fixtureId: "PSER-008",
    label: "Environmental or drainage topic requiring specialist review",
    categories: ["ENVIRONMENTAL_REVIEW_MATERIALS"],
    evidencePosture: {
      sourceRights: "INTERNAL_ANALYSIS_ONLY",
      freshness: "UNDATED",
      supportLevel: "CONTEXTUAL",
      conflictStatus: "INSUFFICIENT_INFORMATION_TO_RECONCILE",
      supersessionStatus: "NOT_APPLICABLE",
      limitationCategories: ["INCOMPLETE_TEMPORAL_COVERAGE", "PROFESSIONAL_VERIFICATION_REQUIRED"],
      provenanceComplete: true,
      attributionRequired: false,
      publicUseEligibility: "INTERNAL_ONLY",
    },
    dispositions: ["FRESHNESS_REVIEW_REQUIRED", "PROFESSIONAL_REVIEW_REQUIRED", "CONDITION_CONCLUSION_PROHIBITED", "UNRESOLVED"],
    professionalReviewCategories: ["ENVIRONMENTAL", "ENGINEERING", "INSPECTION"],
    unresolvedQuestions: ["Which environmental, drainage, soil, or moisture questions require qualified review?"],
    blockedUseWarnings: ["No environmental, safety, hazard, soil, drainage, or condition conclusion is authorized."],
  }),
  fixture({
    fixtureId: "PSER-009",
    label: "Stale evidence",
    categories: ["MAINTENANCE_AND_REPAIR_DOCUMENTATION", "WARRANTIES_AND_SERVICE_RECORDS"],
    evidencePosture: {
      sourceRights: "INTERNAL_ANALYSIS_ONLY",
      freshness: "STALE",
      supportLevel: "CONTEXTUAL",
      conflictStatus: "NO_KNOWN_CONFLICT",
      supersessionStatus: "HISTORICALLY_VALID",
      limitationCategories: ["STALE_EVIDENCE", "PROFESSIONAL_VERIFICATION_REQUIRED"],
      provenanceComplete: true,
      attributionRequired: false,
      publicUseEligibility: "INTERNAL_ONLY",
    },
    dispositions: ["FRESHNESS_REVIEW_REQUIRED", "DOCUMENTATION_INCOMPLETE", "INTERNAL_ONLY"],
    professionalReviewCategories: ["INSPECTION"],
    unresolvedQuestions: ["Which older maintenance or service records require current confirmation?"],
    blockedUseWarnings: ["Stale evidence creates review prompts only and cannot support current condition conclusions."],
  }),
  fixture({
    fixtureId: "PSER-010",
    label: "Undated evidence",
    categories: ["SELLER_DISCLOSURES"],
    evidencePosture: {
      sourceRights: "INTERNAL_ANALYSIS_ONLY",
      freshness: "UNDATED",
      supportLevel: "CONTEXTUAL",
      conflictStatus: "NO_KNOWN_CONFLICT",
      supersessionStatus: "NOT_APPLICABLE",
      limitationCategories: ["INCOMPLETE_TEMPORAL_COVERAGE", "PROFESSIONAL_VERIFICATION_REQUIRED"],
      provenanceComplete: true,
      attributionRequired: false,
      publicUseEligibility: "INTERNAL_ONLY",
    },
    dispositions: ["FRESHNESS_REVIEW_REQUIRED", "PROFESSIONAL_REVIEW_REQUIRED", "INTERNAL_ONLY"],
    professionalReviewCategories: ["LEGAL"],
    unresolvedQuestions: ["Which disclosure materials have effective dates or require broker/legal review?"],
    blockedUseWarnings: ["Undated evidence must not be treated as current or disclosure sufficiency."],
  }),
  fixture({
    fixtureId: "PSER-011",
    label: "Superseded evidence",
    categories: ["WARRANTIES_AND_SERVICE_RECORDS"],
    evidencePosture: {
      sourceRights: "INTERNAL_ANALYSIS_ONLY",
      freshness: "STALE",
      supportLevel: "CONTEXTUAL",
      conflictStatus: "SUPERSEDED_EVIDENCE",
      supersessionStatus: "SUPERSEDED_BY_NEWER",
      limitationCategories: ["SUPERSEDED_EVIDENCE", "STALE_EVIDENCE"],
      provenanceComplete: true,
      attributionRequired: false,
      publicUseEligibility: "INTERNAL_ONLY",
    },
    dispositions: ["FRESHNESS_REVIEW_REQUIRED", "DOCUMENTATION_INCOMPLETE", "INTERNAL_ONLY"],
    professionalReviewCategories: ["INSPECTION"],
    unresolvedQuestions: ["Which newer document supersedes this record for current review?"],
    blockedUseWarnings: ["Superseded evidence is preserved historically and does not create current support."],
  }),
  fixture({
    fixtureId: "PSER-012",
    label: "Conflicting records",
    categories: ["PERMITS_AND_MUNICIPAL_RECORDS", "SELLER_DISCLOSURES"],
    evidencePosture: {
      sourceRights: "UNKNOWN_OR_UNRESOLVED",
      freshness: "AGING",
      supportLevel: "CONTEXTUAL",
      conflictStatus: "MATERIAL_CONFLICT",
      supersessionStatus: "CURRENT_VERSION",
      limitationCategories: ["UNRESOLVED_CONFLICT", "UNCERTAIN_RIGHTS", "PROFESSIONAL_VERIFICATION_REQUIRED"],
      provenanceComplete: false,
      attributionRequired: false,
      publicUseEligibility: "UNRESOLVED",
    },
    dispositions: ["CONFLICT_REVIEW_REQUIRED", "RIGHTS_UNRESOLVED", "PROFESSIONAL_REVIEW_REQUIRED", "UNRESOLVED"],
    professionalReviewCategories: ["MUNICIPAL", "LEGAL"],
    unresolvedQuestions: ["Which conflicting records should be reviewed by qualified municipal, broker, or legal sources?"],
    blockedUseWarnings: ["Conflicts remain unresolved; the system does not choose an automatic winner."],
  }),
  fixture({
    fixtureId: "PSER-013",
    label: "Unknown source rights",
    categories: ["TAX_AND_ASSESSMENT_RECORDS"],
    evidencePosture: {
      sourceRights: "UNKNOWN_OR_UNRESOLVED",
      freshness: "CURRENT",
      supportLevel: "CONTEXTUAL",
      conflictStatus: "NO_KNOWN_CONFLICT",
      supersessionStatus: "CURRENT_VERSION",
      limitationCategories: ["UNCERTAIN_RIGHTS"],
      provenanceComplete: true,
      attributionRequired: false,
      publicUseEligibility: "UNRESOLVED",
    },
    dispositions: ["RIGHTS_UNRESOLVED", "PUBLIC_USE_BLOCKED", "INTERNAL_ONLY"],
    professionalReviewCategories: ["EVIDENCE_RIGHTS_REVIEW", "TAX"],
    unresolvedQuestions: ["Which tax or assessment materials are permitted for internal review or public display?"],
    blockedUseWarnings: ["Unknown source rights fail closed."],
  }),
  fixture({
    fixtureId: "PSER-014",
    label: "Internal-only evidence",
    categories: ["MARKET_CONTEXT_MATERIALS"],
    evidencePosture: {
      sourceRights: "INTERNAL_ANALYSIS_ONLY",
      freshness: "CURRENT",
      supportLevel: "CONTEXTUAL",
      conflictStatus: "COMPATIBLE_EVIDENCE",
      supersessionStatus: "CURRENT_VERSION",
      limitationCategories: ["NON_PUBLIC_USE_RESTRICTION", "CITYWIDE_NOT_PROPERTY_SPECIFIC"],
      provenanceComplete: true,
      attributionRequired: false,
      publicUseEligibility: "INTERNAL_ONLY",
    },
    dispositions: ["INTERNAL_ONLY", "FUTURE_INTEGRATION_CANDIDATE"],
    professionalReviewCategories: ["EVIDENCE_RIGHTS_REVIEW"],
    unresolvedQuestions: ["Which market-context materials remain internal-only and citywide rather than property-specific?"],
    blockedUseWarnings: ["Internal-only market context does not become property-specific support."],
  }),
  fixture({
    fixtureId: "PSER-015",
    label: "Attribution-required evidence",
    categories: ["SURVEYS_AND_SITE_PLANS"],
    evidencePosture: {
      sourceRights: "PUBLIC_DISPLAY_PERMITTED_WITH_ATTRIBUTION",
      freshness: "AGING",
      supportLevel: "CONTEXTUAL",
      conflictStatus: "NO_KNOWN_CONFLICT",
      supersessionStatus: "CURRENT_VERSION",
      limitationCategories: ["ATTRIBUTION_REQUIRED", "PROFESSIONAL_VERIFICATION_REQUIRED"],
      provenanceComplete: true,
      attributionRequired: true,
      publicUseEligibility: "INTERNAL_ONLY",
    },
    dispositions: ["DOCUMENTATION_CATEGORY_READY", "FRESHNESS_REVIEW_REQUIRED", "PROFESSIONAL_REVIEW_REQUIRED", "INTERNAL_ONLY"],
    professionalReviewCategories: ["TITLE", "LEGAL"],
    unresolvedQuestions: ["Which survey or site-plan materials require attribution and professional review?"],
    blockedUseWarnings: ["Attribution posture is preserved, but this phase remains internal only."],
  }),
  fixture({
    fixtureId: "PSER-016",
    label: "Prohibited public-use evidence",
    categories: ["TAX_AND_ASSESSMENT_RECORDS", "OWNERSHIP_AND_TITLE_DOCUMENTATION_QUESTIONS"],
    evidencePosture: {
      sourceRights: "PROHIBITED",
      freshness: "CURRENT",
      supportLevel: "UNSUPPORTED",
      conflictStatus: "NO_KNOWN_CONFLICT",
      supersessionStatus: "CURRENT_VERSION",
      limitationCategories: ["NON_PUBLIC_USE_RESTRICTION"],
      provenanceComplete: true,
      attributionRequired: false,
      publicUseEligibility: "BLOCKED",
    },
    dispositions: ["PUBLIC_USE_BLOCKED", "RIGHTS_UNRESOLVED", "DEFERRED"],
    professionalReviewCategories: ["EVIDENCE_RIGHTS_REVIEW", "LEGAL"],
    unresolvedQuestions: ["Which evidence must remain blocked from public use?"],
    blockedUseWarnings: ["Prohibited public-use evidence remains blocked."],
  }),
  fixture({
    fixtureId: "PSER-017",
    label: "Property identity ambiguity",
    categories: ["CANONICAL_PROPERTY_IDENTITY"],
    propertyIdentity: {
      identityConfidencePosture: "AMBIGUOUS",
      ambiguity: Object.freeze(["Same display address pattern could refer to multiple property records in a future system."]),
      limitations: Object.freeze(["Identity is ambiguous; activation is blocked until separately resolved."]),
    },
    evidencePosture: {
      sourceRights: "INTERNAL_ANALYSIS_ONLY",
      freshness: "NOT_APPLICABLE",
      supportLevel: "UNSUPPORTED",
      conflictStatus: "INSUFFICIENT_INFORMATION_TO_RECONCILE",
      supersessionStatus: "NOT_APPLICABLE",
      limitationCategories: ["PROFESSIONAL_VERIFICATION_REQUIRED"],
      provenanceComplete: false,
      attributionRequired: false,
      publicUseEligibility: "INTERNAL_ONLY",
    },
    dispositions: ["IDENTITY_UNRESOLVED", "PROFESSIONAL_REVIEW_REQUIRED", "PUBLIC_USE_BLOCKED", "UNRESOLVED"],
    professionalReviewCategories: ["TITLE", "LEGAL"],
    unresolvedQuestions: ["What governed identity evidence would be required before future property-specific use?"],
    blockedUseWarnings: ["Ambiguous identity blocks public activation and customer-specific analysis."],
  }),
  fixture({
    fixtureId: "PSER-018",
    label: "Customer-data dependency blocked",
    categories: ["OCCUPANCY_AND_ACCESS_CONSIDERATIONS"],
    evidencePosture: {
      sourceRights: "UNKNOWN_OR_UNRESOLVED",
      freshness: "UNDATED",
      supportLevel: "UNSUPPORTED",
      conflictStatus: "INSUFFICIENT_INFORMATION_TO_RECONCILE",
      supersessionStatus: "NOT_APPLICABLE",
      limitationCategories: ["UNAVAILABLE_UNDERLYING_SOURCE", "NON_PUBLIC_USE_RESTRICTION"],
      provenanceComplete: false,
      attributionRequired: false,
      publicUseEligibility: "BLOCKED",
    },
    dispositions: ["CUSTOMER_DATA_REQUIRED_BUT_UNAUTHORIZED", "PUBLIC_USE_BLOCKED", "DEFERRED"],
    professionalReviewCategories: ["LEGAL"],
    unresolvedQuestions: ["Which occupancy or access details require customer-provided information that is not authorized in this phase?"],
    blockedUseWarnings: ["Customer data is not accepted, stored, or used."],
  }),
  fixture({
    fixtureId: "PSER-019",
    label: "Provider dependency blocked",
    categories: ["TAX_AND_ASSESSMENT_RECORDS", "PERMITS_AND_MUNICIPAL_RECORDS"],
    evidencePosture: {
      sourceRights: "UNKNOWN_OR_UNRESOLVED",
      freshness: "UNDATED",
      supportLevel: "UNSUPPORTED",
      conflictStatus: "INSUFFICIENT_INFORMATION_TO_RECONCILE",
      supersessionStatus: "NOT_APPLICABLE",
      limitationCategories: ["UNCERTAIN_RIGHTS", "UNAVAILABLE_UNDERLYING_SOURCE"],
      provenanceComplete: false,
      attributionRequired: false,
      publicUseEligibility: "BLOCKED",
    },
    dispositions: ["PROVIDER_DEPENDENCY_BLOCKED", "RIGHTS_UNRESOLVED", "PUBLIC_USE_BLOCKED", "DEFERRED"],
    professionalReviewCategories: ["MUNICIPAL", "EVIDENCE_RIGHTS_REVIEW"],
    unresolvedQuestions: ["Which future provider or public-record dependencies require separate authorization?"],
    blockedUseWarnings: ["Provider access and public-record retrieval are blocked."],
  }),
  fixture({
    fixtureId: "PSER-020",
    label: "Valuation-output prohibition",
    categories: ["MARKET_CONTEXT_MATERIALS", "LISTING_PREPARATION_DOCUMENTS"],
    evidencePosture: {
      sourceRights: "INTERNAL_ANALYSIS_ONLY",
      freshness: "CURRENT",
      supportLevel: "CONTEXTUAL",
      conflictStatus: "NO_KNOWN_CONFLICT",
      supersessionStatus: "CURRENT_VERSION",
      limitationCategories: ["CITYWIDE_NOT_PROPERTY_SPECIFIC", "PROFESSIONAL_VERIFICATION_REQUIRED"],
      provenanceComplete: true,
      attributionRequired: false,
      publicUseEligibility: "INTERNAL_ONLY",
    },
    dispositions: ["VALUATION_PROHIBITED", "INTERNAL_ONLY", "PROFESSIONAL_REVIEW_REQUIRED"],
    professionalReviewCategories: ["APPRAISAL"],
    unresolvedQuestions: ["Which market context may inform questions without producing a value, price, net sheet, or timing recommendation?"],
    blockedUseWarnings: ["Automated valuation, listing price, comparable-sale calculation, and seller net sheet outputs are prohibited."],
  }),
  fixture({
    fixtureId: "PSER-021",
    label: "Condition-conclusion prohibition",
    categories: ["INSPECTION_AND_SPECIALIST_REPORTS", "MAINTENANCE_AND_REPAIR_DOCUMENTATION", "UTILITIES_AND_SYSTEMS_DOCUMENTATION"],
    evidencePosture: {
      sourceRights: "INTERNAL_ANALYSIS_ONLY",
      freshness: "AGING",
      supportLevel: "CONTEXTUAL",
      conflictStatus: "NO_KNOWN_CONFLICT",
      supersessionStatus: "CURRENT_VERSION",
      limitationCategories: ["PROFESSIONAL_VERIFICATION_REQUIRED"],
      provenanceComplete: true,
      attributionRequired: false,
      publicUseEligibility: "INTERNAL_ONLY",
    },
    dispositions: ["CONDITION_CONCLUSION_PROHIBITED", "PROFESSIONAL_REVIEW_REQUIRED", "INTERNAL_ONLY"],
    professionalReviewCategories: ["INSPECTION", "PROPERTY_CONDITION_SPECIALIST"],
    unresolvedQuestions: ["Which condition topics should be taken to an inspector or specialist?"],
    blockedUseWarnings: ["No condition conclusion, repair score, required-repair list, or marketability conclusion is authorized."],
  }),
  fixture({
    fixtureId: "PSER-022",
    label: "No-score and no-ranking guard",
    categories: ["LISTING_PREPARATION_DOCUMENTS"],
    evidencePosture: {
      sourceRights: "INTERNAL_ANALYSIS_ONLY",
      freshness: "NOT_APPLICABLE",
      supportLevel: "CONTEXTUAL",
      conflictStatus: "NO_KNOWN_CONFLICT",
      supersessionStatus: "NOT_APPLICABLE",
      limitationCategories: ["NON_PUBLIC_USE_RESTRICTION"],
      provenanceComplete: true,
      attributionRequired: false,
      publicUseEligibility: "INTERNAL_ONLY",
    },
    dispositions: ["INTERNAL_ONLY", "VALUATION_PROHIBITED", "CONDITION_CONCLUSION_PROHIBITED"],
    professionalReviewCategories: ["EVIDENCE_RIGHTS_REVIEW"],
    unresolvedQuestions: ["Which preparation categories exist without producing a score, grade, or ranking?"],
    blockedUseWarnings: ["Dispositions are not scores, grades, lead rankings, or transaction probabilities."],
  }),
  fixture({
    fixtureId: "PSER-023",
    label: "Public non-exposure guard",
    categories: ["UNRESOLVED_INFORMATION", "PROFESSIONAL_VERIFICATION_NEEDS"],
    evidencePosture: {
      sourceRights: "RESTRICTED",
      freshness: "UNDATED",
      supportLevel: "UNSUPPORTED",
      conflictStatus: "INSUFFICIENT_INFORMATION_TO_RECONCILE",
      supersessionStatus: "NOT_APPLICABLE",
      limitationCategories: ["NON_PUBLIC_USE_RESTRICTION", "UNCERTAIN_RIGHTS"],
      provenanceComplete: false,
      attributionRequired: false,
      publicUseEligibility: "BLOCKED",
    },
    dispositions: ["PUBLIC_USE_BLOCKED", "RIGHTS_UNRESOLVED", "UNRESOLVED"],
    professionalReviewCategories: ["EVIDENCE_RIGHTS_REVIEW", "LEGAL"],
    unresolvedQuestions: ["Which internal readiness details must remain non-public?"],
    blockedUseWarnings: ["No public route, API, evidence category, fixture content, readiness disposition, or internal summary is exposed."],
  }),
  fixture({
    fixtureId: "PSER-024",
    label: "Mixed evidence-set summary",
    categories: [
      "CANONICAL_PROPERTY_IDENTITY",
      "IMPROVEMENTS_AND_RENOVATION_RECORDS",
      "PERMITS_AND_MUNICIPAL_RECORDS",
      "SELLER_DISCLOSURES",
      "INSURANCE_QUESTIONS_AND_RECORDS",
      "PROFESSIONAL_VERIFICATION_NEEDS",
    ],
    evidencePosture: {
      sourceRights: "UNKNOWN_OR_UNRESOLVED",
      freshness: "AGING",
      supportLevel: "CONTEXTUAL",
      conflictStatus: "UNRESOLVED_CONFLICT",
      supersessionStatus: "CURRENT_VERSION",
      limitationCategories: ["UNRESOLVED_CONFLICT", "UNCERTAIN_RIGHTS", "PROFESSIONAL_VERIFICATION_REQUIRED"],
      provenanceComplete: false,
      attributionRequired: false,
      publicUseEligibility: "UNRESOLVED",
    },
    dispositions: [
      "DOCUMENTATION_INCOMPLETE",
      "RIGHTS_UNRESOLVED",
      "FRESHNESS_REVIEW_REQUIRED",
      "CONFLICT_REVIEW_REQUIRED",
      "PROFESSIONAL_REVIEW_REQUIRED",
      "FUTURE_INTEGRATION_CANDIDATE",
      "UNRESOLVED",
    ],
    professionalReviewCategories: ["TITLE", "INSURANCE", "INSPECTION", "MUNICIPAL", "LEGAL"],
    unresolvedQuestions: ["Which mixed evidence categories need rights, freshness, conflict, and professional-review resolution?"],
    blockedUseWarnings: ["The summary is internal and conclusion-free."],
  }),
]);
