import type { AgentBriefingNextAction } from "./agentBriefingComposition";
import type { AgentSellerPreparationRequest } from "./agentSellerPreparationAdmission";

export const AGENT_SELLER_PROFESSIONAL_PLAYBOOK_STATUS = "REIE_AGENT_SELLER_CONSULTATION_PREPARATION_READINESS_AND_ADMISSION_MVV" as const;
export type AgentSellerGuide = Readonly<{ keyQuestions: readonly string[]; talkingPoints: readonly string[]; factsToConfirm: readonly string[]; professionalCheckpoints: readonly string[]; expectedOutcome: string; }>;
export type AgentSellerPlaybookSection = Readonly<{ id: string; title: string; level: "CORE" | "DETAIL"; emphasis: "STANDARD" | "SELECTED_PRIORITY"; summary: string; prompts: readonly string[]; guide?: AgentSellerGuide; }>;
export type AgentSellerConsultationAgendaStep = Readonly<{ id: string; title: string; summary: string; guide: AgentSellerGuide; }>;
export type AgentSellerProfessionalPlaybook = Readonly<{ status: typeof AGENT_SELLER_PROFESSIONAL_PLAYBOOK_STATUS; sections: readonly AgentSellerPlaybookSection[]; consultationAgenda: readonly AgentSellerConsultationAgendaStep[]; nextActionPlan: Readonly<{ agentActions: readonly string[]; sellerClarifications: readonly string[]; professionalVerification: readonly string[]; atlasContinuations: readonly AgentBriefingNextAction[]; }>; protectedBoundaries: Readonly<{ customerData: false; persistence: false; providerActivity: false; recommendation: false; suitability: false; fairHousingInference: false; pricingConclusion: false; legalTaxConclusion: false; }>; }>;
const boundaries = Object.freeze({ customerData: false, persistence: false, providerActivity: false, recommendation: false, suitability: false, fairHousingInference: false, pricingConclusion: false, legalTaxConclusion: false } as const);
const guide = (keyQuestions: string[], talkingPoints: string[], factsToConfirm: string[], professionalCheckpoints: string[], expectedOutcome: string): AgentSellerGuide => ({ keyQuestions, talkingPoints, factsToConfirm, professionalCheckpoints, expectedOutcome });
const selected = (request: AgentSellerPreparationRequest, priority: AgentSellerPreparationRequest["priorities"][number]) => request.priorities.includes(priority) ? "SELECTED_PRIORITY" as const : "STANDARD" as const;
const section = (id: string, title: string, level: "CORE" | "DETAIL", emphasis: "STANDARD" | "SELECTED_PRIORITY", summary: string, prompts: string[], sectionGuide?: AgentSellerGuide): AgentSellerPlaybookSection => ({ id, title, level, emphasis, summary, prompts, ...(sectionGuide ? { guide: sectionGuide } : {}) });

export function buildAgentSellerProfessionalPlaybook(request: AgentSellerPreparationRequest): AgentSellerProfessionalPlaybook {
  const movingTowardMarket = request.position === "MOVING_TOWARD_MARKET";
  const sections = [
    section("seller-preparation-frame", "Seller preparation frame", "CORE", "STANDARD", "Build a confident, evidence-aware consultation around the Seller's stated goals, questions, and next decisions.", ["Use the complete playbook as the consultation foundation.", "Give selected topics Priority Focus while keeping supporting questions available for the live conversation."], guide(["What outcome would make this consultation most useful?", "Which selected topics deserve Priority Focus today?"], ["Use the Seller's reported context and confirm material facts through the appropriate professional path."], ["Stated goals, selected topics, and open questions"], ["Qualified professionals for legal, tax, title, lending, inspection, insurance, or record questions"], "A prepared conversation with clear emphasis and accountable next steps.")),
    section("seller-position-readiness", "Seller position & readiness", "CORE", "STANDARD", movingTowardMarket ? "The conversation is preparing to move toward market. Organize the open readiness facts before treating a launch sequence as final." : "The conversation begins with discovery. Clarify the decision posture before assuming a sale path.", ["Confirm what a successful sale process would mean to the Seller.", "Identify stated timing, flexibility, decision participants, and plan-changing facts."], guide(["What would make this sale successful for you?", "What is prompting the conversation now?"], ["Keep the stated objective separate from an assumed recommendation or urgency."], ["Objective, timing, participants, flexibility"], ["Qualified advice where an objective raises legal, tax, estate, or trust questions"], "A shared, explicit consultation objective and readiness posture.")),
    section("seller-discovery-questions", "Questions to understand the Seller", "CORE", "STANDARD", "Use the selected topics to draw out explicit goals, uncertainties, and decision constraints.", ["Ask which parts of the decision are already clear and which remain unresolved.", "Ask what could cause the timing or plan to change."], guide(["Which parts of the decision are already clear?", "Which parts are still being worked through?"], ["Use reported answers only; do not infer household, financial, or location preferences."], ["Stated objectives, timing milestones, decision roles"], ["Professional questions by category, not diagnosis"], "A documented question set for the live discussion.")),
    section("property-condition-preparation", "Property / condition preparation", "CORE", selected(request, "PROPERTY_CONDITION_PREPARATION"), "Organize reported condition and preparation questions before relying on property facts or setting a presentation plan.", ["Separate known repairs, deferred maintenance, presentation, staging, systems, permits, and improvements.", "Identify records, inspections, insurance, municipal, HOA, or specialist questions that need confirmation."], guide(["Which known repairs, maintenance, or improvements should be discussed?", "Which records or permits are available and which need verification?"], ["Property preparation is not a finding about condition, compliance, value, or marketability."], ["Reported condition, improvements, records, occupancy and access context"], ["Inspector, engineer, insurer, municipality, county, HOA, or title professional as applicable"], "A sequenced property-preparation discussion without unsupported conclusions.")),
    section("pricing-market-preparation", "Pricing & market preparation", "CORE", selected(request, "PRICING_DISCUSSION"), "Use admitted, dated evidence to prepare the Agent's professional pricing analysis and market discussion.", ["Identify property facts, condition differences, listing competition, inventory, days-on-market, and comparable-analysis inputs to verify.", "Use current market evidence only with its visible date, freshness, and limitations."], guide(["Which property facts must be confirmed before pricing analysis?", "Which current market questions are most important to the Seller?"], ["Prepare evidence for the Agent's judgment and keep valuation certainty or sale-outcome guarantees outside this briefing."], ["Property configuration, records, condition differences, current dated market evidence"], ["Agent professional judgment and any qualified record source needed for facts"], "A bounded evidence plan for a future pricing discussion.")),
    section("property-facts-records", "Property facts / records", "CORE", selected(request, "PROPERTY_FACTS_RECORDS"), "Organize property identity, configuration, size, lot, year built, history, tax, HOA, permit, title, insurance, and improvement questions without inferring missing facts.", ["Mark records as client-reported, public or third-party, conflicting, incomplete, or awaiting verification.", "Verify material records before relying on them in the Seller consultation." ]),
    section("selling-process-roadmap", "Selling process roadmap", "CORE", selected(request, "SELLING_PROCESS"), "Prepare the Seller for a governed sequence from consultation through property and record preparation, market analysis, listing preparation, launch, active-market activity, offer review, contract, due diligence, title, and closing.", ["For each stage, explain what happens, what the Seller should expect, what the Agent prepares, and what may require another professional.", "Keep representation, disclosures, and transaction-specific requirements subject to current governing-document review."]),
    section("showing-launch-preparation", "Showing / launch preparation", "DETAIL", selected(request, "SHOWING_LAUNCH_PREPARATION"), "Use only explicit information to discuss access, occupancy, presentation, photos, communication, feedback, and listing-readiness checkpoints.", ["Clarify showing preferences and constraints without making assumptions about occupancy or household circumstances.", "Prepare launch-readiness questions before treating a launch date as committed." ]),
    section("seller-proceeds-financial-discussion", "Seller proceeds / financial discussion", "DETAIL", selected(request, "SELLER_PROCEEDS_FINANCIAL_QUESTIONS"), "Frame payoff, lien, selling-cost category, title, tax, and proceeds questions as process education and professional verification, not tax, legal, lending, or net-proceeds advice.", ["Identify information the Seller may need to obtain from a lienholder or title professional.", "Do not promise proceeds, costs, tax treatment, or a financial result." ]),
    section("offer-review-education", "Offer-review education", "DETAIL", selected(request, "OFFER_REVIEW_PROCESS"), "Explain a future evaluation framework for price, financing, earnest money, inspection structure, appraisal, contingencies, closing timing, possession, concessions, and other material terms.", ["Keep this educational until a separately authorized offer-review workflow applies.", "Do not predict acceptance, recommend an offer outcome, or treat one term as dispositive." ]),
    section("professional-checkpoints", "Due-diligence / professional checkpoints", "DETAIL", selected(request, "PROFESSIONAL_QUESTIONS"), "Organize the question and evidence needed for title, lender or lienholder, inspector or engineer, insurance, tax, attorney, municipal or county, HOA, and other qualified roles.", ["State the question category and the evidence to bring to the qualified professional.", "Keep professional referral activity outside this preparation workflow." ]),
    section("representation-process", "Representation / process checkpoints", "DETAIL", selected(request, "REPRESENTATION_BROKERAGE_PROCESS"), "Prepare the Agent to discuss applicable brokerage relationship, representation, listing documentation, compensation or process, disclosures, and authorized next steps using current governing documents.", ["Do not represent any requirement as settled without current governing-document and firm-policy review.", "Keep this page educational and session-only." ]),
  ];
  const agenda = [
    { id: "open-align", title: "Open and align", summary: "Confirm what the Seller wants the consultation to accomplish.", guide: guide(["What would make this conversation useful today?"], ["Set a professional, explicit agenda."], ["Objective and decision participants"], ["None unless the stated objective needs qualified review"], "A clear consultation purpose.") },
    { id: "objective-timing", title: "Understand objective and timing", summary: "Clarify goals, timing, decision process, and plan-changing facts.", guide: guide(["Is the timing a target or a flexible window?", "What milestones could move it?"], ["Treat the stated timing as the Seller's current planning horizon."], ["Timing and flexibility"], ["Tax, legal, estate, or lender questions as applicable"], "A usable timing and decision frame.") },
    { id: "property", title: "Understand the property", summary: "Clarify property facts, condition, records, improvements, and preparation needs.", guide: guide(["What is known about condition, records, and improvements?"], ["Separate reported context from verified facts."], ["Identity, condition, records, permits, HOA"], ["Inspector, municipality, HOA, insurer, or title professional as needed"], "A property-preparation checklist.") },
    { id: "pricing-market", title: "Pricing / market preparation", summary: "Establish what evidence is needed and how market positioning will be evaluated.", guide: guide(["Which facts and dated market evidence are needed before pricing analysis?"], ["Pricing is an Agent judgment supported by evidence, not an automatic result."], ["Comparable inputs, competition, condition differences, freshness"], ["Agent review and qualified record verification"], "A bounded pricing-preparation plan.") },
    { id: "process-launch-offers", title: "Selling process / launch / offer review", summary: "Explain preparation through active market and future offer review.", guide: guide(["Which process and launch questions should be clarified now?"], ["Future offer review considers multiple material terms."], ["Access, presentation, communication, offer education"], ["Title, lender, inspection, and other qualified review when applicable"], "A shared process roadmap.") },
    { id: "representation-next", title: "Representation / professional questions / next steps", summary: "Clarify process responsibilities, professional checkpoints, and the next action plan.", guide: guide(["Which representation or documentation questions need current review?"], ["Keep legal, tax, title, lending, and property findings with qualified professionals."], ["Open questions and accountable next steps"], ["Title, lienholder, tax, attorney, municipal, HOA, inspector, insurance"], "A concrete, bounded next-action plan.") },
  ];
  const atlasContinuations: AgentBriefingNextAction[] = [{ id: "seller-atlas-property", category: "Future ATLAS action", text: "Prepare property facts and records.", href: "/agent/prepare/property" }, { id: "seller-atlas-market", category: "Future ATLAS action", text: "Prepare dated market context.", href: "/agent/prepare/market" }];
  if (request.cityContext) atlasContinuations.push({ id: "seller-atlas-place", category: "Future ATLAS action", text: `Prepare neutral ${request.cityContext} location context.`, href: "/agent/prepare/place" });
  return Object.freeze({ status: AGENT_SELLER_PROFESSIONAL_PLAYBOOK_STATUS, sections: Object.freeze(sections), consultationAgenda: Object.freeze(agenda), nextActionPlan: Object.freeze({ agentActions: ["Confirm the Seller's timing flexibility and decision participants.", "Organize the property facts and record questions needed for preparation.", "Prepare the market and pricing-evidence discussion without treating it as a recommendation."], sellerClarifications: ["Clarify known condition, repair, access, occupancy, and preparation questions.", "Clarify which process, launch, proceeds, or offer-review questions matter most."], professionalVerification: ["Identify title, payoff, lien, tax, legal, inspection, insurance, municipal, county, or HOA questions for qualified review."], atlasContinuations: Object.freeze(atlasContinuations) }), protectedBoundaries: boundaries });
}
