import type { AgentBriefingNextAction } from "./agentBriefingComposition";
import { AGENT_LISTING_PREPARATION_PRIORITIES, type AgentListingPreparationPriority, type AgentListingPreparationRequest } from "./agentListingPreparationAdmission";

export const AGENT_LISTING_PROFESSIONAL_PLAYBOOK_STATUS = "REIE_AGENT_LISTING_PREPARATION_READINESS_AND_ADMISSION_MVV" as const;
export type AgentListingGuide = Readonly<{ keyQuestions: readonly string[]; talkingPoints: readonly string[]; factsToConfirm: readonly string[]; professionalCheckpoints: readonly string[]; expectedOutcome: string }>;
export type AgentListingPlaybookSection = Readonly<{ id: string; title: string; level: "CORE" | "DETAIL"; emphasis: "STANDARD" | "SELECTED_PRIORITY"; summary: string; prompts: readonly string[]; guide: AgentListingGuide }>;
export type AgentListingProfessionalPlaybook = Readonly<{
  status: typeof AGENT_LISTING_PROFESSIONAL_PLAYBOOK_STATUS;
  sections: readonly AgentListingPlaybookSection[];
  preparationAgenda: readonly Readonly<{ id: string; title: string; summary: string; guide: AgentListingGuide }>[];
  nextActionPlan: Readonly<{ agentActions: readonly string[]; sellerClarifications: readonly string[]; professionalVerification: readonly string[]; atlasContinuations: readonly AgentBriefingNextAction[] }>;
  protectedBoundaries: Readonly<{ customerData: false; persistence: false; providerActivity: false; propertyIdentity: false; mlsActivity: false; publicActivation: false; recommendation: false; suitability: false; fairHousingInference: false; pricingConclusion: false; legalTaxConclusion: false }>;
}>;

const boundaries = Object.freeze({ customerData: false, persistence: false, providerActivity: false, propertyIdentity: false, mlsActivity: false, publicActivation: false, recommendation: false, suitability: false, fairHousingInference: false, pricingConclusion: false, legalTaxConclusion: false } as const);
const guide = (keyQuestions: string[], talkingPoints: string[], factsToConfirm: string[], professionalCheckpoints: string[], expectedOutcome: string): AgentListingGuide => ({ keyQuestions, talkingPoints, factsToConfirm, professionalCheckpoints, expectedOutcome });
const priority = (request: AgentListingPreparationRequest, value: AgentListingPreparationPriority) => request.priorities.includes(value) ? "SELECTED_PRIORITY" as const : "STANDARD" as const;
const section = (id: string, title: string, level: "CORE" | "DETAIL", emphasis: "STANDARD" | "SELECTED_PRIORITY", summary: string, prompts: string[], sectionGuide: AgentListingGuide): AgentListingPlaybookSection => ({ id, title, level, emphasis, summary, prompts, guide: sectionGuide });

export function buildAgentListingProfessionalPlaybook(request: AgentListingPreparationRequest): AgentListingProfessionalPlaybook {
  const sections = [
    section("listing-preparation-frame", "Listing preparation frame", "CORE", "STANDARD", "Organize the complete preparation playbook around explicit Agent-selected emphasis while keeping every topic available.", ["Treat a selected topic as Priority Focus, not an exclusion of the rest of the preparation work.", "Do not enter, retain, or infer a seller, property, address, MLS identifier, or customer profile in this surface."], guide(["What needs to be ready before a possible launch can be considered?"], ["Use this surface for preparation sequencing, not a listing or launch decision."], ["Agent-confirmed property context only; no identity retained"], ["Current governing documents and qualified professionals where applicable"], "A bounded preparation frame with no new customer or property record.")),
    section("listing-readiness", "Pre-listing readiness", "CORE", priority(request, "PRE_LISTING_READINESS"), "Define the open work, decision participants, timing questions, and dependencies before treating any plan as settled.", ["Separate a preparation horizon from a launch commitment.", "Identify what must be verified or reviewed before the next decision."], guide(["What would make the property ready for the next agent-reviewed decision?"], ["Keep Seller objectives, timing, and assumptions explicit and revisable."], ["Stated horizon, decision participants, plan-changing facts"], ["Legal, tax, title, and representation questions as appropriate"], "A transparent list of readiness dependencies.")),
    section("listing-property-facts", "Property facts & records", "CORE", priority(request, "PROPERTY_FACTS_RECORDS"), "Identify fact categories that need current-source confirmation without importing or concluding on property data here.", ["Separate reported facts from verified records.", "Treat ambiguity, conflicts, stale records, and unsupported jurisdiction as unresolved."], guide(["Which property facts or records are necessary for the next review?"], ["A source registry entry or source-quality label does not itself permit use."], ["Identity, source, rights, freshness, evidence, attribution, conflict, boundary, jurisdiction"], ["County, municipal, HOA, title, and other authoritative or qualified sources as relevant"], "A verification question set rather than a property conclusion.")),
    section("listing-condition", "Condition, repairs & improvements", "CORE", priority(request, "CONDITION_REPAIRS_IMPROVEMENTS"), "Organize reported condition and preparation questions without prioritizing repairs, estimating return, or diagnosing a property.", ["Record questions for qualified inspection or trade review.", "Do not convert a reported concern into a condition, repair, or improvement conclusion."], guide(["Which reported conditions need professional review before they affect a plan?"], ["Preparation questions are not repair recommendations or value conclusions."], ["Inspection, engineering, permits, insurance, and contractor evidence status"], ["Qualified inspector, engineer, contractor, insurer, or municipal professional"], "A professional-review queue for condition questions.")),
    section("listing-presentation", "Presentation, media & access", "CORE", priority(request, "PRESENTATION_MEDIA_ACCESS"), "Prepare presentation and access questions while keeping media rights, attribution, occupancy, and approval status explicit.", ["Ask what access and occupancy constraints must be respected.", "Do not create, acquire, publish, reuse, or activate photography, media, or marketing assets."], guide(["What access, presentation, media-rights, and attribution questions remain open?"], ["Unknown rights or attribution always fail closed for use."], ["Written permission, rights scope, attribution, freshness, seller approval, access constraints"], ["Approved vendors and brokerage/brand review where required"], "A rights-aware media and access checklist with no asset activity.")),
    section("listing-documents", "Disclosures & documents", "DETAIL", priority(request, "DISCLOSURES_DOCUMENTS"), "Identify document and disclosure questions; do not determine completeness, sufficiency, legal effect, or representation status.", ["Use current governing documents rather than a generic checklist as the authority.", "Escalate property-specific or legal questions for qualified review."], guide(["Which documents or disclosures require current-form or professional review?"], ["This preparation is not a disclosure generator or legal conclusion."], ["Current form/version, required acknowledgements, open material-fact questions"], ["Brokerage, legal, and other qualified professionals"], "A bounded document-review agenda.")),
    section("listing-pricing-market", "Pricing & market inputs", "DETAIL", priority(request, "PRICING_MARKET_INPUTS"), "Prepare the factual questions an agent may need to review without estimating value, recommending price, forecasting outcomes, or claiming a market conclusion.", ["Keep property evidence and dated market context separate.", "Treat missing, stale, conflicting, or non-comparable material as a review trigger."], guide(["Which verified property and dated market inputs would make a future agent discussion better informed?"], ["No automated valuation, pricing advice, or forecast is produced."], ["Evidence source, effective date, scope, conflict state, and limitations"], ["Agent professional judgment and appropriate current data/evidence review"], "A source-aware input agenda, not a price conclusion.")),
    section("listing-marketing-data", "Marketing & listing-data preparation", "DETAIL", priority(request, "MARKETING_LISTING_DATA_PREPARATION"), "Prepare factual, approval, Fair Housing, rights, brand, and MLS questions without drafting content, entering MLS data, advertising, or activating marketing.", ["Use factual property-focused language and avoid protected-class or suitability content.", "MLS and marketing activity remain outside this preparation surface."], guide(["Which factual fields, approvals, rights, and compliance questions need review before any future marketing activity?"], ["No marketing recommendation, copy, campaign, MLS entry, or publication is generated."], ["Factual support, rights, attribution, approvals, Fair Housing and brokerage/MLS requirements"], ["Brokerage, MLS, marketing, and legal/compliance professionals as appropriate"], "A compliance-aware preparation checklist with no marketing action.")),
    section("listing-launch", "Launch & showing checkpoints", "DETAIL", priority(request, "LAUNCH_CHECKPOINTS"), "Sequence verification and approval checkpoints without authorizing a launch, showing, public route, Search, Map, Property, or marketing activation.", ["Identify what could change timing, access, or readiness.", "An existing route or source identity does not create activation authority."], guide(["Which open facts, approvals, and professional checks must be resolved before a future launch discussion?"], ["Launch timing remains a human decision after appropriate review."], ["Access, occupancy, rights, document, verification, and approval statuses"], ["Seller, brokerage, title, insurance, inspection, HOA, municipal, and other qualified professionals"], "An explicit no-activation checkpoint sequence.")),
    section("listing-professional-verification", "Professional verification", "DETAIL", priority(request, "PROFESSIONAL_VERIFICATION"), "Keep title, lien, payoff, HOA, municipal, insurance, tax, inspection, legal, representation, and other professional questions visible rather than implied.", ["Assign questions to the appropriate qualified source or professional.", "Do not infer a result from a missing answer or generalized material."], guide(["Who is responsible for each unresolved professional determination?"], ["Professional checkpoints are questions for review, not automated determinations."], ["Responsible professional, evidence status, date, conflict, and unresolved questions"], ["Title/lienholder, tax/legal, inspection, insurance, municipal, HOA, brokerage, and other qualified professionals"], "An accountable professional verification path.")),
  ];
  const agenda = [
    { id: "listing-agenda-readiness", title: "Frame the preparation", summary: "Confirm the session is for an agent-confirmed seller property and identify the next decision to support.", guide: sections[0].guide },
    { id: "listing-agenda-evidence", title: "Separate facts from open evidence", summary: "List factual categories that need source, freshness, rights, attribution, boundary, jurisdiction, and conflict review.", guide: sections[2].guide },
    { id: "listing-agenda-condition", title: "Route condition and presentation questions", summary: "Keep repair, improvement, presentation, media, and access questions with the appropriate qualified review path.", guide: sections[3].guide },
    { id: "listing-agenda-documents", title: "Check documents and professional dependencies", summary: "Identify current governing-document, title, lien, tax, legal, insurance, HOA, municipal, and inspection checkpoints.", guide: sections[5].guide },
    { id: "listing-agenda-market", title: "Prepare future agent review inputs", summary: "Separate dated market and property evidence from any pricing, marketing, launch, or representation conclusion.", guide: sections[6].guide },
    { id: "listing-agenda-next", title: "Set no-activation next actions", summary: "Sequence verification and future Agent preparation without creating or activating a listing workflow.", guide: sections[8].guide },
  ];
  const atlasContinuations: AgentBriefingNextAction[] = [
    { id: "listing-next-seller", category: "Future ATLAS action", text: "Seller Preparation", href: "/agent/prepare/seller" },
    { id: "listing-next-place", category: "Future ATLAS action", text: "Location Preparation for separately governed neutral place context", href: "/agent/prepare/place" },
    { id: "listing-next-property", category: "Future ATLAS action", text: "Property Preparation for independently admitted existing public records only", href: "/agent/prepare/property" },
    { id: "listing-next-market", category: "Future ATLAS action", text: "Market Preparation for dated context", href: "/agent/prepare/market" },
  ];
  return Object.freeze({
    status: AGENT_LISTING_PROFESSIONAL_PLAYBOOK_STATUS,
    sections: Object.freeze(sections),
    preparationAgenda: Object.freeze(agenda),
    nextActionPlan: Object.freeze({
      agentActions: ["Review the selected Priority Focus topics and keep the complete playbook available.", "Record no seller, customer, property, address, MLS, or source data in this session-only surface.", "Route any material fact, conflict, rights, or professional question to the appropriate current review path."],
      sellerClarifications: ["Clarify timing, access, decision participants, and stated preparation constraints during the live Seller discussion.", "Confirm any future use of property, media, documents, or marketing material through the appropriate process."],
      professionalVerification: ["Title, lien, payoff, ownership, tax, legal, estate, trust, HOA, municipal, permit, inspection, insurance, disclosure, and representation questions require qualified current review.", "Unknown rights, stale information, conflicts, ambiguous identity, and unsupported jurisdiction remain unresolved and unavailable for reliance."],
      atlasContinuations,
    }),
    protectedBoundaries: boundaries,
  });
}

export { AGENT_LISTING_PREPARATION_PRIORITIES };
