import type { AgentConversationPreparationInput } from './agentConversationPreparationComposition';
import type { ReieDecisionEvidenceItem } from '../reieDecisionEvidenceClassification';

const fact = {
  id: 'market-fact', label: 'Supplied market context', value: 'Current governed snapshot', classification: 'FACT' as const,
  provenance: { origin: 'GOVERNED_SOURCE_FACT' as const, reference: 'market-snapshot', sourceId: 'SRC-MARKET', freshness: 'CURRENT' as const, rights: 'REVIEWED' as const }, visibility: 'ADMIN_ONLY' as const, verification: 'NOT_REQUIRED' as const, prohibitedUse: ['No recommendation'],
};
const assumption = { ...fact, id: 'assumption', label: 'Explicit assumption', value: 'Review timing', classification: 'USER_ASSUMPTION' as const, provenance: { origin: 'EXPLICIT_CUSTOMER_INPUT' as const, reference: 'explicit', sourceId: null, freshness: 'NOT_APPLICABLE' as const, rights: 'NOT_APPLICABLE' as const } };
const missing = { ...fact, id: 'missing', label: 'Missing evidence', value: null, classification: 'NOT_AVAILABLE' as const, provenance: { origin: 'NONE' as const, reference: null, sourceId: null, freshness: 'UNKNOWN' as const, rights: 'UNKNOWN_OR_UNRESOLVED' as const }, visibility: 'DATA_INSUFFICIENT' as const, verification: 'REQUIRED' as const };
const professional = { ...fact, id: 'professional', label: 'Inspection verification', classification: 'PROFESSIONAL_VERIFICATION_REQUIRED' as const, verification: 'REQUIRED' as const };
const handoff = { id: 'inspection', role: 'INSPECTOR' as const, questionCategory: 'Property condition verification', whyVerificationIsNeeded: 'Supplied evidence requires professional review.', informationToBring: ['Supplied property facts'], whatReieCannotDetermine: ['Condition conclusion'], customerSelectedHandoff: false, agentPreparationOnly: true, contextItemIds: ['professional'], providerRecommendation: false as const, ranking: false as const, referralRelationship: false as const, automaticCommunication: false as const };
const context = (items: readonly ReieDecisionEvidenceItem[] = [fact]) => ({ role: 'ADMIN' as const, selectedGoals: [], items: items.map((evidence, index) => ({ id: `context-${index}`, domain: 'MARKET' as const, evidence })), professionalHandoffs: [], sourcePosture: { state: 'EXPLICIT_SOURCE_STATE' as const, rights: 'EXPLICIT_REVIEWED' as const, freshness: 'CURRENT' as const }, persistencePosture: 'NOT_PERSISTED' as const, hiddenTransferPosture: 'PROHIBITED' as const, prohibitedOutputs: ['No recommendation'] });
const marketPacket = { status: 'READY_FOR_AGENT_REVIEW' } as AgentConversationPreparationInput['marketPlacePacket'];
const sellerPacket = { status: 'READY_FOR_AGENT_REVIEW' } as AgentConversationPreparationInput['sellerUpdatePacket'];
const offerPacket = { status: 'OFFER_PREPARATION_READINESS_IMPLEMENTED' } as AgentConversationPreparationInput['offerPreparation'];

export const AGENT_CONVERSATION_PREPARATION_FIXTURES = {
  marketComplete: { preparationType: 'MARKET_PLACE', purpose: 'Prepare a neutral internal market review.', context: context(), surfaceReferences: ['MARKET', 'DECISION_GUIDES', 'SOURCES'], assumptions: [assumption], limitations: ['Point-in-time evidence.'], openQuestions: ['Which source date should be verified?'], conflicts: [], professionalHandoffs: [], marketPlacePacket: marketPacket, sellerUpdatePacket: null, offerPreparation: null },
  marketIncomplete: { preparationType: 'MARKET_PLACE', purpose: 'Prepare a neutral internal market review.', context: context([missing]), surfaceReferences: ['MARKET', 'SOURCES'], assumptions: [assumption], limitations: ['Evidence is incomplete.'], openQuestions: ['What should be verified?'], conflicts: [], professionalHandoffs: [], marketPlacePacket: marketPacket, sellerUpdatePacket: null, offerPreparation: null },
  sellerMissingFacts: { preparationType: 'SELLER_UPDATE_REVIEW', purpose: 'Prepare supplied seller update facts for review.', context: context([missing]), surfaceReferences: ['SELL', 'PROPERTY', 'MARKET', 'SOURCES'], assumptions: [], limitations: ['Missing facts remain missing.'], openQuestions: ['Which listing facts need verification?'], conflicts: [], professionalHandoffs: [], marketPlacePacket: null, sellerUpdatePacket: sellerPacket, offerPreparation: null },
  offerProfessional: { preparationType: 'OFFER_PREPARATION_REVIEW', purpose: 'Prepare neutral offer verification questions.', context: context([professional]), surfaceReferences: ['BUY', 'PROPERTY', 'MARKET', 'SOURCES'], assumptions: [], limitations: ['Professional review remains required.'], openQuestions: ['What requires professional verification?'], conflicts: [], professionalHandoffs: [handoff], marketPlacePacket: null, sellerUpdatePacket: null, offerPreparation: offerPacket },
  conflictingEvidence: { preparationType: 'MARKET_PLACE', purpose: 'Prepare a neutral internal market review.', context: context(), surfaceReferences: ['MARKET'], assumptions: [], limitations: [], openQuestions: ['What source should be reviewed?'], conflicts: ['Two supplied sources conflict.'], professionalHandoffs: [], marketPlacePacket: marketPacket, sellerUpdatePacket: null, offerPreparation: null },
  prohibitedFairHousing: { preparationType: 'MARKET_PLACE', purpose: 'Prepare the best fit neighborhood review.', context: context(), surfaceReferences: ['MARKET'], assumptions: [], limitations: [], openQuestions: [], conflicts: [], professionalHandoffs: [], marketPlacePacket: marketPacket, sellerUpdatePacket: null, offerPreparation: null },
  prohibitedRecommendation: { preparationType: 'MARKET_PLACE', purpose: 'Prepare a recommendation.', context: context(), surfaceReferences: ['MARKET'], assumptions: [], limitations: [], openQuestions: [], conflicts: [], professionalHandoffs: [], marketPlacePacket: marketPacket, sellerUpdatePacket: null, offerPreparation: null },
  prohibitedOfferAdvice: { preparationType: 'OFFER_PREPARATION_REVIEW', purpose: 'Prepare neutral offer questions.', context: context(), surfaceReferences: ['BUY'], assumptions: [], limitations: [], openQuestions: ['What offer price should be used?'], conflicts: [], professionalHandoffs: [], marketPlacePacket: null, sellerUpdatePacket: null, offerPreparation: offerPacket },
  prohibitedPersistence: { preparationType: 'MARKET_PLACE', purpose: 'Prepare neutral review.', context: context(), surfaceReferences: ['MARKET'], assumptions: [], limitations: [], openQuestions: [], conflicts: [], professionalHandoffs: [], marketPlacePacket: marketPacket, sellerUpdatePacket: null, offerPreparation: null, persistence: true } as unknown as AgentConversationPreparationInput,
  prohibitedCrmIdentity: { preparationType: 'MARKET_PLACE', purpose: 'Prepare neutral review.', context: context(), surfaceReferences: ['MARKET'], assumptions: [], limitations: [], openQuestions: [], conflicts: [], professionalHandoffs: [], marketPlacePacket: marketPacket, sellerUpdatePacket: null, offerPreparation: null, customerName: 'Blocked' } as unknown as AgentConversationPreparationInput,
  prohibitedHiddenTransfer: { preparationType: 'MARKET_PLACE', purpose: 'Prepare neutral review.', context: context(), surfaceReferences: ['MARKET'], assumptions: [], limitations: [], openQuestions: [], conflicts: [], professionalHandoffs: [], marketPlacePacket: marketPacket, sellerUpdatePacket: null, offerPreparation: null, hiddenRouteContext: 'blocked' } as unknown as AgentConversationPreparationInput,
  unsupported: { preparationType: 'BUYER', purpose: 'Unsupported first MVV context.', context: context(), surfaceReferences: ['BUY'], assumptions: [], limitations: [], openQuestions: [], conflicts: [], professionalHandoffs: [], marketPlacePacket: null, sellerUpdatePacket: null, offerPreparation: null } as unknown as AgentConversationPreparationInput,
} as const;
