import { requireAdvisoryEvidenceFixture } from "./fixtureHelpers.js";
import { type AdvisoryOperatingFixture } from "./advisoryOperatingReadiness.js";

export const ADVISORY_OPERATING_READINESS_FIXTURES: readonly AdvisoryOperatingFixture[] = Object.freeze([
  {
    fixtureId: "cross_city_comparison_citywide_limitations",
    label: "Cross-city comparison discussion with citywide limitations",
    decisionContexts: ["COMPARE_MARKETS", "VERIFY"],
    requestedSurfaces: ["CROSS_CITY_COMPARISON", "CITY_OR_DECISION_GUIDE_CONTEXT", "MARKET_CONTEXT", "ADVISORY_HANDOFF"],
    openQuestionCategories: ["MARKET_AND_GEOGRAPHIC_CONTEXT", "EVIDENCE_LIMITATIONS", "NEXT_ACTIONS"],
    evidenceItems: [requireAdvisoryEvidenceFixture("eligible_with_limitations")],
    requestedProfessionalEscalations: [],
    requestedNextSteps: ["COMPARE_ALTERNATIVES", "REVIEW_MORE_REIE_CONTEXT"],
    insufficientInformation: false,
    prohibitedOutputProbe: false,
  },
  {
    fixtureId: "buyer_financing_lender_escalation",
    label: "Buyer and Financing Readiness discussion with lender escalation",
    decisionContexts: ["BUY", "FINANCE", "PROFESSIONAL_REVIEW"],
    requestedSurfaces: ["BUYER_GUIDANCE", "BUYER_FINANCING_READINESS", "SEARCH", "ADVISORY_HANDOFF"],
    openQuestionCategories: ["FINANCING", "GOALS_AND_DECISION_CONTEXT", "PROFESSIONAL_VERIFICATION"],
    evidenceItems: [requireAdvisoryEvidenceFixture("public_use_complete_provenance")],
    requestedProfessionalEscalations: ["LENDING"],
    requestedNextSteps: ["VERIFY_WITH_QUALIFIED_SOURCE", "CONTINUE_TO_ADVISORY"],
    insufficientInformation: false,
    prohibitedOutputProbe: false,
  },
  {
    fixtureId: "seller_readiness_document_questions",
    label: "Seller Readiness discussion with property and document questions",
    decisionContexts: ["SELL", "PREPARE", "VERIFY"],
    requestedSurfaces: ["SELLER_GUIDANCE", "SELLER_READINESS", "PROPERTY_CONTEXT", "ADVISORY_HANDOFF"],
    openQuestionCategories: ["SELLER_PREPARATION", "PROPERTY_SPECIFIC_REVIEW", "PROFESSIONAL_VERIFICATION"],
    evidenceItems: [requireAdvisoryEvidenceFixture("eligible_with_limitations")],
    requestedProfessionalEscalations: ["TITLE", "INSPECTION"],
    requestedNextSteps: ["GATHER_RELEVANT_DOCUMENTS", "SPEAK_WITH_APPROPRIATE_PROFESSIONAL"],
    insufficientInformation: false,
    prohibitedOutputProbe: false,
  },
  {
    fixtureId: "stale_or_undated_verification",
    label: "Stale or undated evidence requiring verification",
    decisionContexts: ["VERIFY"],
    requestedSurfaces: ["MARKET_CONTEXT", "ADVISORY_HANDOFF"],
    openQuestionCategories: ["EVIDENCE_LIMITATIONS", "TIMING_AND_SEQUENCING"],
    evidenceItems: [requireAdvisoryEvidenceFixture("stale_evidence"), requireAdvisoryEvidenceFixture("undated_evidence")],
    requestedProfessionalEscalations: ["EVIDENCE_RIGHTS_REVIEW"],
    requestedNextSteps: ["VERIFY_WITH_QUALIFIED_SOURCE", "PAUSE_UNTIL_INFORMATION_VERIFIED"],
    insufficientInformation: false,
    prohibitedOutputProbe: false,
  },
  {
    fixtureId: "conflicting_evidence_preservation",
    label: "Conflicting evidence requiring both sides to remain visible",
    decisionContexts: ["VERIFY", "PROFESSIONAL_REVIEW"],
    requestedSurfaces: ["CITY_OR_DECISION_GUIDE_CONTEXT", "ADVISORY_HANDOFF"],
    openQuestionCategories: ["EVIDENCE_LIMITATIONS", "SOURCE_AND_RIGHTS", "PROFESSIONAL_VERIFICATION"],
    evidenceItems: [requireAdvisoryEvidenceFixture("conflicting_evidence_a"), requireAdvisoryEvidenceFixture("conflicting_evidence_b")],
    requestedProfessionalEscalations: ["EVIDENCE_RIGHTS_REVIEW"],
    requestedNextSteps: ["VERIFY_WITH_QUALIFIED_SOURCE", "PAUSE_UNTIL_INFORMATION_VERIFIED"],
    insufficientInformation: false,
    prohibitedOutputProbe: false,
  },
  {
    fixtureId: "internal_only_not_customer_ready",
    label: "Internal-only evidence that cannot be used with a customer",
    decisionContexts: ["VERIFY"],
    requestedSurfaces: ["ADVISORY_HANDOFF"],
    openQuestionCategories: ["SOURCE_AND_RIGHTS", "EVIDENCE_LIMITATIONS"],
    evidenceItems: [requireAdvisoryEvidenceFixture("internal_only_evidence")],
    requestedProfessionalEscalations: ["EVIDENCE_RIGHTS_REVIEW"],
    requestedNextSteps: ["PAUSE_UNTIL_INFORMATION_VERIFIED"],
    insufficientInformation: false,
    prohibitedOutputProbe: false,
  },
  {
    fixtureId: "attribution_required_context",
    label: "Attribution-required evidence",
    decisionContexts: ["VERIFY"],
    requestedSurfaces: ["CITY_OR_DECISION_GUIDE_CONTEXT", "MARKET_CONTEXT"],
    openQuestionCategories: ["SOURCE_AND_RIGHTS", "EVIDENCE_LIMITATIONS"],
    evidenceItems: [requireAdvisoryEvidenceFixture("attribution_required_evidence")],
    requestedProfessionalEscalations: ["EVIDENCE_RIGHTS_REVIEW"],
    requestedNextSteps: ["REVIEW_MORE_REIE_CONTEXT"],
    insufficientInformation: false,
    prohibitedOutputProbe: false,
  },
  {
    fixtureId: "property_specific_specialist_review",
    label: "Property-specific question requiring specialist review",
    decisionContexts: ["BUY", "SELL", "PROFESSIONAL_REVIEW"],
    requestedSurfaces: ["PROPERTY_CONTEXT", "BUYER_GUIDANCE", "SELLER_GUIDANCE", "ADVISORY_HANDOFF"],
    openQuestionCategories: ["PROPERTY_SPECIFIC_REVIEW", "PROFESSIONAL_VERIFICATION"],
    evidenceItems: [requireAdvisoryEvidenceFixture("eligible_with_limitations")],
    requestedProfessionalEscalations: ["APPRAISAL", "INSPECTION", "ENGINEERING", "INSURANCE", "ENVIRONMENTAL", "MUNICIPAL", "HOA", "PROPERTY_CONDITION_SPECIALIST"],
    requestedNextSteps: ["REVIEW_PROPERTY_OR_NEIGHBORHOOD", "SPEAK_WITH_APPROPRIATE_PROFESSIONAL"],
    insufficientInformation: false,
    prohibitedOutputProbe: false,
  },
  {
    fixtureId: "grand_plan_sequencing",
    label: "Grand Plan sequencing discussion",
    decisionContexts: ["GRAND_PLAN_COORDINATION", "PREPARE"],
    requestedSurfaces: ["GRAND_PLAN", "BUYER_GUIDANCE", "SELLER_GUIDANCE", "ADVISORY_HANDOFF"],
    openQuestionCategories: ["TIMING_AND_SEQUENCING", "NEXT_ACTIONS", "GOALS_AND_DECISION_CONTEXT"],
    evidenceItems: [requireAdvisoryEvidenceFixture("public_use_complete_provenance")],
    requestedProfessionalEscalations: ["TAX", "LEGAL"],
    requestedNextSteps: ["COMPARE_ALTERNATIVES", "CONTINUE_TO_ADVISORY"],
    insufficientInformation: false,
    prohibitedOutputProbe: false,
  },
  {
    fixtureId: "insufficient_information_advisory",
    label: "Advisory conversation with insufficient information",
    decisionContexts: ["PROFESSIONAL_REVIEW", "VERIFY"],
    requestedSurfaces: ["ADVISORY_HANDOFF", "MARKET_CONTEXT"],
    openQuestionCategories: ["GOALS_AND_DECISION_CONTEXT", "EVIDENCE_LIMITATIONS", "PROFESSIONAL_VERIFICATION"],
    evidenceItems: [requireAdvisoryEvidenceFixture("unknown_rights_evidence")],
    requestedProfessionalEscalations: ["EVIDENCE_RIGHTS_REVIEW"],
    requestedNextSteps: ["PAUSE_UNTIL_INFORMATION_VERIFIED", "VERIFY_WITH_QUALIFIED_SOURCE"],
    insufficientInformation: true,
    prohibitedOutputProbe: false,
  },
  {
    fixtureId: "mixed_journey_without_customer_profiling",
    label: "Mixed journey context without customer profiling",
    decisionContexts: ["COMPARE_MARKETS", "BUY", "FINANCE", "SELL", "GRAND_PLAN_COORDINATION"],
    requestedSurfaces: ["CROSS_CITY_COMPARISON", "BUYER_FINANCING_READINESS", "SELLER_READINESS", "GRAND_PLAN", "ADVISORY_HANDOFF"],
    openQuestionCategories: ["GOALS_AND_DECISION_CONTEXT", "FINANCING", "SELLER_PREPARATION", "TIMING_AND_SEQUENCING", "NEXT_ACTIONS"],
    evidenceItems: [requireAdvisoryEvidenceFixture("eligible_with_limitations"), requireAdvisoryEvidenceFixture("attribution_required_evidence")],
    requestedProfessionalEscalations: ["LENDING", "TAX", "LEGAL"],
    requestedNextSteps: ["REVIEW_MORE_REIE_CONTEXT", "COMPARE_ALTERNATIVES", "CONTINUE_TO_ADVISORY"],
    insufficientInformation: false,
    prohibitedOutputProbe: false,
  },
  {
    fixtureId: "prohibited_output_guard",
    label: "Prohibited-output case proving no urgency, lead score, recommendation, or sales script",
    decisionContexts: ["VERIFY"],
    requestedSurfaces: ["ADVISORY_HANDOFF"],
    openQuestionCategories: ["NEXT_ACTIONS", "EVIDENCE_LIMITATIONS"],
    evidenceItems: [requireAdvisoryEvidenceFixture("blocked_evidence"), requireAdvisoryEvidenceFixture("superseded_evidence")],
    requestedProfessionalEscalations: ["EVIDENCE_RIGHTS_REVIEW"],
    requestedNextSteps: ["PAUSE_UNTIL_INFORMATION_VERIFIED"],
    insufficientInformation: true,
    prohibitedOutputProbe: true,
  },
]);
