import type { AgentPropertyConversationCandidate } from './agent-advisory-workbench/agentPropertyConversationPreparation';

export const CURRENT_COMPETING_LISTING_CONTEXT_FIXTURES = Object.freeze({
  validSubject: Object.freeze({
    property: Object.freeze({
      origin: 'REPOSITORY_PROPERTY',
      resolvedPropertyCount: 1,
      slug: 'fixture-current-competing-subject',
      mlsId: 'MLS-W6-SUBJECT-1',
      address: '1000 Pearl Street',
      city: 'Boulder',
      state: 'CO',
      zip: '80302',
      status: 'Active',
      isPrivateExclusive: false,
      price: 1000000,
      beds: 3,
      baths: 2.5,
      sqft: 2200,
      lotSize: 0.14,
      yearBuilt: 1998,
      propertyType: 'Residential',
      neighborhood: 'Central Boulder',
    }),
    sourcePosture: Object.freeze({
      sourceId: 'AGENT_PROPERTY_LISTING_SOURCE_V1',
      sourceClass: 'EXISTING_REPOSITORY_LISTING_FACTS',
      listingReference: 'MLS-W6-SUBJECT-1',
      observedAt: '2026-08-25T12:00:00.000Z',
      freshness: 'CURRENT',
      completeness: 'COMPLETE',
      conflict: 'NO_CONFLICT',
      rights: 'CERTIFIED_EXISTING_REPOSITORY_USE',
      certification: 'PROPERTY_PRODUCT_CERTIFIED',
    }),
  } satisfies AgentPropertyConversationCandidate),
  nullSubjectPrice: Object.freeze({
    property: Object.freeze({
      origin: 'REPOSITORY_PROPERTY',
      resolvedPropertyCount: 1,
      slug: 'fixture-current-competing-subject-null-price',
      mlsId: 'MLS-W6-SUBJECT-NULL-PRICE',
      address: '1001 Pearl Street',
      city: 'Boulder',
      state: 'CO',
      zip: '80302',
      status: 'Active',
      isPrivateExclusive: false,
      price: null,
      beds: 3,
      baths: 2.5,
      sqft: null,
      lotSize: null,
      yearBuilt: 1998,
      propertyType: 'Residential',
      neighborhood: null,
    }),
    sourcePosture: Object.freeze({
      sourceId: 'AGENT_PROPERTY_LISTING_SOURCE_V1',
      sourceClass: 'EXISTING_REPOSITORY_LISTING_FACTS',
      listingReference: 'MLS-W6-SUBJECT-NULL-PRICE',
      observedAt: '2026-08-25T12:00:00.000Z',
      freshness: 'CURRENT',
      completeness: 'INCOMPLETE',
      conflict: 'NO_CONFLICT',
      rights: 'CERTIFIED_EXISTING_REPOSITORY_USE',
      certification: 'PROPERTY_PRODUCT_CERTIFIED',
    }),
  } satisfies AgentPropertyConversationCandidate),
  missingListingIdentity: Object.freeze({
    property: Object.freeze({
      origin: 'REPOSITORY_PROPERTY',
      resolvedPropertyCount: 1,
      slug: 'fixture-current-competing-subject-missing-identity',
      mlsId: null,
      address: '1002 Pearl Street',
      city: 'Boulder',
      state: 'CO',
      zip: '80302',
      status: 'Active',
      isPrivateExclusive: false,
      price: 1000000,
      beds: 3,
      baths: 2,
      sqft: 2100,
      lotSize: null,
      yearBuilt: 1990,
      propertyType: 'Residential',
      neighborhood: null,
    }),
    sourcePosture: Object.freeze({
      sourceId: 'AGENT_PROPERTY_LISTING_SOURCE_V1',
      sourceClass: 'EXISTING_REPOSITORY_LISTING_FACTS',
      listingReference: null,
      observedAt: '2026-08-25T12:00:00.000Z',
      freshness: 'CURRENT',
      completeness: 'COMPLETE',
      conflict: 'NO_CONFLICT',
      rights: 'CERTIFIED_EXISTING_REPOSITORY_USE',
      certification: 'PROPERTY_PRODUCT_CERTIFIED',
    }),
  } satisfies AgentPropertyConversationCandidate),
});
