import type { MarketMetricDefinition, MarketMetricObservation } from './marketMetricDefinitionEvidence';

export const CERTIFIED_MARKET_METRIC_DEFINITION_FIXTURE: MarketMetricDefinition = Object.freeze({
  metricDefinitionId: 'fixture.certified.active-inventory.v1',
  canonicalName: 'Certified active inventory',
  displayLabel: 'Active inventory',
  metricFamily: 'INVENTORY',
  sourceFamily: 'MLS',
  sourceConcept: 'Fixture-only certified active listing count',
  unit: 'Listings',
  aggregationMethod: 'Count of documented active listings at a stated cutoff.',
  populationDefinition: 'Fixture-only residential listing population.',
  listingStatusScope: 'Fixture-only documented active statuses.',
  propertyTypeScope: 'Fixture-only residential property types.',
  geographicScope: 'Fixture-only city boundary.',
  timeBasis: 'POINT_IN_TIME',
  periodDefinition: 'Fixture-only source cutoff.',
  priceBasis: 'NOT_APPLICABLE',
  domBasis: 'NOT_APPLICABLE',
  activityConcept: 'ACTIVE_INVENTORY',
  calculationMethodVersion: 'fixture-certified-calculation-v1',
  sourceMethodologyReference: 'fixture-certified-methodology-v1',
  semanticStatus: 'CERTIFIED',
  admissionStatus: 'ADMITTED_FOR_LIMITED_USE',
  historicalComparisonStatus: 'CERTIFIED_COMPARABLE',
  freshnessContract: 'Fixture-only current source cutoff.',
  limitations: Object.freeze([]),
  prohibitedInterpretations: Object.freeze(['NO_FORECAST', 'NO_PROPERTY_VALUATION'] as const),
  allowedUses: Object.freeze(['DISPLAY_RAW_OBSERVATION', 'HISTORICAL_COMPARISON'] as const),
});

const compatibleBase: MarketMetricObservation = Object.freeze({
  observationId: 'market-observation-2026-08-a',
  metricDefinitionId: 'atlas.city-market.inventory-signal.v1',
  value: 42,
  geographyId: 'boulder-co-housing-market',
  geographyType: 'CITY',
  propertyPopulation: 'Detached and attached residential listings in the documented source population.',
  statusPopulation: 'Documented active listing statuses.',
  periodStart: '2026-07-01',
  periodEnd: '2026-07-31',
  asOfDate: '2026-07-31',
  sourceDate: '2026-07-31',
  atlasObservedDate: '2026-08-01',
  freshness: 'CURRENT',
  sourceEvidenceId: 'fixture-market-source-evidence-v1',
  sourceMethodologyReference: 'fixture-market-methodology-v1',
  calculationMethodVersion: 'fixture-calculation-v1',
  verificationState: 'CERTIFIED',
  limitations: Object.freeze([]),
});

export const MARKET_METRIC_DEFINITION_EVIDENCE_FIXTURES = Object.freeze({
  unresolvedInventory: compatibleBase,
  unresolvedDom: Object.freeze({
    ...compatibleBase,
    observationId: 'market-observation-unresolved-dom',
    metricDefinitionId: 'atlas.city-market.days-on-market-signal.v1',
    value: 21,
  }),
  unresolvedPrice: Object.freeze({
    ...compatibleBase,
    observationId: 'market-observation-unresolved-price',
    metricDefinitionId: 'atlas.city-market.price-signal.v1',
    value: 800000,
  }),
  compatibleLeft: Object.freeze({ ...compatibleBase, metricDefinitionId: CERTIFIED_MARKET_METRIC_DEFINITION_FIXTURE.metricDefinitionId }),
  compatibleRight: Object.freeze({ ...compatibleBase, observationId: 'market-observation-2026-09-b', metricDefinitionId: CERTIFIED_MARKET_METRIC_DEFINITION_FIXTURE.metricDefinitionId, periodStart: '2026-08-01', periodEnd: '2026-08-31', asOfDate: '2026-08-31', sourceDate: '2026-08-31', atlasObservedDate: '2026-09-01' }),
  incompatibleDefinition: Object.freeze({ ...compatibleBase, observationId: 'market-observation-incompatible-definition', metricDefinitionId: 'atlas.city-market.price-signal.v1' }),
  incompleteMetadata: Object.freeze({ ...compatibleBase, observationId: 'market-observation-incomplete-metadata', metricDefinitionId: CERTIFIED_MARKET_METRIC_DEFINITION_FIXTURE.metricDefinitionId, sourceMethodologyReference: null, calculationMethodVersion: null, propertyPopulation: null, statusPopulation: null, periodStart: null, asOfDate: null }),
  limitedComparison: Object.freeze({ ...compatibleBase, observationId: 'market-observation-limited-comparison', metricDefinitionId: CERTIFIED_MARKET_METRIC_DEFINITION_FIXTURE.metricDefinitionId, verificationState: 'PROFESSIONAL_VERIFICATION_REQUIRED' }),
});
