import type { Prisma, PrismaClient } from '@prisma/client';

import { strategyFingerprint, MULTI_DIMENSIONAL_STRATEGY_BRIEF_V1 } from './multiDimensionalStrategySuite';
import type { PersistableOutputFixture } from './outputPersistenceFoundation';

export class StrategyOutputError extends Error { constructor(readonly code: 'INVALID_REQUEST' | 'OWNERSHIP_DENIED' | 'REVIEW_REQUIRED', message: string) { super(message); } }

export async function buildStrategyBriefFixture(prisma: PrismaClient, ownerAgentSubject: string, raw: Readonly<{ analysisId: string; alternativeIds: readonly string[] }>): Promise<PersistableOutputFixture> {
  const ids = [...new Set(raw.alternativeIds)]; if (!raw.analysisId || ids.length < 2 || ids.length !== raw.alternativeIds.length) throw new StrategyOutputError('INVALID_REQUEST', 'Select at least two distinct reviewed strategies.');
  const analysis = await prisma.strategyAnalysis.findFirst({ where: { id: raw.analysisId, ownerAgentSubject }, include: { alternatives: { where: { id: { in: ids } }, include: { results: { orderBy: { versionOrdinal: 'desc' }, take: 1 }, propertyRoles: true, dependencies: true } } } });
  if (!analysis || analysis.alternatives.length !== ids.length) throw new StrategyOutputError('OWNERSHIP_DENIED', 'A selected strategy is unavailable to this Agent.');
  const selected = ids.map((id) => analysis.alternatives.find((item) => item.id === id)!);
  if (selected.some((item) => item.lifecycleState !== 'AGENT_REVIEWED' || !item.results[0] || item.results[0].inputFingerprint !== item.inputFingerprint)) throw new StrategyOutputError('REVIEW_REQUIRED', 'Every Strategy Brief alternative requires a current Agent-reviewed result.');
  const sellerFinancialResultIds = [...new Set(selected.flatMap((item) => {
    const existing = (item.inputSnapshot as Record<string, unknown>).existing as Record<string, unknown> | undefined;
    return typeof existing?.sellerFinancialResultId === 'string' ? [existing.sellerFinancialResultId] : [];
  }))];
  if (sellerFinancialResultIds.length) {
    const ownedSellerFinancialResults = await prisma.sellerFinancialResult.count({ where: { id: { in: sellerFinancialResultIds }, ownerAgentSubject } });
    if (ownedSellerFinancialResults !== sellerFinancialResultIds.length) throw new StrategyOutputError('OWNERSHIP_DENIED', 'A Seller Financial dependency is unavailable to this Agent.');
  }
  const items = selected.map((item) => ({ alternativeId: item.id, alternativeKey: item.alternativeKey, profile: item.strategyProfile, inputFingerprint: item.inputFingerprint, resultId: item.results[0].id, resultFingerprint: item.results[0].resultFingerprint, inputSnapshot: item.inputSnapshot, resultSnapshot: item.results[0].resultSnapshot, propertyRoles: item.propertyRoles }));
  const payload = Object.freeze({ schemaVersion: MULTI_DIMENSIONAL_STRATEGY_BRIEF_V1, analysis: { id: analysis.id, key: analysis.analysisKey, title: analysis.title, engineVersion: analysis.engineVersion, assumptionPolicy: analysis.assumptionPolicy }, selectedComparisonState: items.map(({ alternativeId, alternativeKey, profile, resultId, resultFingerprint }) => ({ alternativeId, alternativeKey, profile, resultId, resultFingerprint })), alternatives: items, qualifier: 'AGENT_INTERNAL_SYNTHETIC_CERTIFICATION', reviewState: 'AGENT_REVIEWED', limitations: ['No automatic strategy recommendation is made.', 'Financing, tax consequences, rental permission, and legal requirements are not determined by this internal decision-support output.'] });
  const contentFingerprint = strategyFingerprint(payload); const selectionRef = items.map((item) => `${item.alternativeId}:${item.resultFingerprint}`).join('|');
  const product = await prisma.outputProduct.findFirst({ where: { ownerAgentSubject, productKind: 'ADVISORY_BRIEFING', audience: 'AGENT_INTERNAL', subjectRef: `StrategyAnalysis:${analysis.id}` }, select: { id: true } });
  const previous = product ? await prisma.outputVersion.findFirst({ where: { productId: product.id, lifecycleState: 'AGENT_REVIEWED' }, orderBy: { versionOrdinal: 'desc' }, select: { id: true } }) : null;
  const dependencies = [
    { upstreamArtifact: `StrategyAnalysis:${analysis.id}`, downstreamArtifact: MULTI_DIMENSIONAL_STRATEGY_BRIEF_V1, dependencyType: 'FINANCIAL_DEPENDENCY' as const, materiality: 'HIGH' as const, versionUsed: `${analysis.engineVersion}|${analysis.assumptionPolicy}`, fieldMetricScope: ['engineVersion', 'assumptionPolicy'], changePolicy: 'A changed strategy engine requires a successor Strategy Brief.', invalidationPolicy: 'RECOMPUTE_REQUIRED' as const, reviewPolicy: 'AGENT_REVIEW_REQUIRED' as const, currentState: 'CURRENT' as const },
    ...sellerFinancialResultIds.map((id) => ({ upstreamArtifact: `SellerFinancialResult:${id}`, downstreamArtifact: MULTI_DIMENSIONAL_STRATEGY_BRIEF_V1, dependencyType: 'FINANCIAL_DEPENDENCY' as const, materiality: 'HIGH' as const, versionUsed: 'SELLER_FINANCIAL_ESTIMATED_SCENARIO_V1', fieldMetricScope: ['saleProceedsCents', 'qualification'], changePolicy: 'A changed seller-financial result requires a successor Strategy Brief.', invalidationPolicy: 'RECOMPUTE_REQUIRED' as const, reviewPolicy: 'AGENT_REVIEW_REQUIRED' as const, currentState: 'CURRENT' as const })),
    ...selected.flatMap((item) => [{ upstreamArtifact: `StrategyAlternative:${item.id}`, downstreamArtifact: MULTI_DIMENSIONAL_STRATEGY_BRIEF_V1, dependencyType: 'AGENT_INPUT_DEPENDENCY' as const, materiality: 'HIGH' as const, versionUsed: item.inputFingerprint, fieldMetricScope: ['inputSnapshot', 'sourceQualification', 'dependencySnapshot'], changePolicy: 'Changed assumptions require a successor Strategy Brief.', invalidationPolicy: 'RECOMPUTE_REQUIRED' as const, reviewPolicy: 'AGENT_REVIEW_REQUIRED' as const, currentState: 'CURRENT' as const }, { upstreamArtifact: `StrategyAlternativeResult:${item.results[0].id}`, downstreamArtifact: MULTI_DIMENSIONAL_STRATEGY_BRIEF_V1, dependencyType: 'FINANCIAL_DEPENDENCY' as const, materiality: 'HIGH' as const, versionUsed: item.results[0].resultFingerprint, fieldMetricScope: ['resultSnapshot', 'calculationVersion'], changePolicy: 'A different immutable strategy result requires a successor Strategy Brief.', invalidationPolicy: 'RECOMPUTE_REQUIRED' as const, reviewPolicy: 'AGENT_REVIEW_REQUIRED' as const, currentState: 'CURRENT' as const }]),
  ];
  return Object.freeze({ sourceVersionRef: `${MULTI_DIMENSIONAL_STRATEGY_BRIEF_V1}:${analysis.id}:${strategyFingerprint(selectionRef)}`, outputProductId: `strategy-brief:${analysis.id}`, productKind: 'ADVISORY_BRIEFING', audience: 'AGENT_INTERNAL', subjectRef: `StrategyAnalysis:${analysis.id}`, purpose: 'Agent-reviewed multi-dimensional real-estate strategy comparison.', displayVersion: `Strategy Brief / ${items.map((item) => item.alternativeKey).join(' vs ')}`, effectiveAsOf: analysis.createdAt.toISOString().slice(0, 10), contentVersion: MULTI_DIMENSIONAL_STRATEGY_BRIEF_V1, compositionVersion: MULTI_DIMENSIONAL_STRATEGY_BRIEF_V1, presentationVisualVersion: 'MULTI_DIMENSIONAL_STRATEGY_AGENT_WORKSPACE_V1', outputContractVersion: MULTI_DIMENSIONAL_STRATEGY_BRIEF_V1, payloadSchemaVersion: MULTI_DIMENSIONAL_STRATEGY_BRIEF_V1, contentFingerprint, contentPayload: payload as unknown as Prisma.JsonObject, lineage: Object.freeze({ strategyAnalysisId: analysis.id, selectedAlternativeResultRefs: selectionRef, sellerFinancialResultRefs: sellerFinancialResultIds.join('|'), ...(previous ? { priorReviewedVersion: `OutputVersion:${previous.id}` } : {}) }), evidence: Object.freeze({ sourceSnapshotRefs: [...items.flatMap((item) => item.propertyRoles.map((role) => `CanonicalPhysicalProperty:${role.canonicalPropertyId}`)), ...sellerFinancialResultIds.map((id) => `SellerFinancialResult:${id}`)], metricRefs: items.map((item) => `StrategyAlternativeResult:${item.resultId}`), analysisRefs: items.map((item) => `StrategyAlternative:${item.alternativeId}`), agentInputRefs: items.map((item) => `StrategyAlternativeInput:${item.alternativeId}:${item.inputFingerprint}`), assumptionRefs: [analysis.engineVersion, analysis.assumptionPolicy, ...items.map((item) => item.inputFingerprint)], limitationRefs: payload.limitations, rightsRefs: ['SYNTHETIC_CERTIFICATION_INTERNAL_ONLY'], freshnessRefs: [`IMMUTABLE_STRATEGY_RESULT_SET:${selectionRef}`], reviewState: 'AGENT_REVIEWED', fingerprint: strategyFingerprint({ contentFingerprint, selectionRef, sellerFinancialResultIds }) }), dependencies, decisionRefs: items.map((item) => `StrategyAlternative:${item.alternativeId}`) });
}
