import type { GeographicObject } from './geographicObjectGovernance';
const boundary = { ranking: false, suitability: false, protectedClassInference: false, propertyAssignment: false, customerPersonalization: false } as const;
const base = (canonicalId: string, canonicalName: string, objectType: GeographicObject['objectType']): GeographicObject => ({ canonicalId, canonicalName, displayName: canonicalName, objectType, aliases: [], jurisdictionStatus: 'NOT_ASSERTED', parentObjectId: null, relationshipType: 'NON_JURISDICTIONAL_CONTEXT', evidenceReferences: ['GOVERNANCE-FIXTURE'], sourceReferences: ['SOURCE-REFERENCE-REQUIRED'], rightsPosture: 'UNKNOWN', freshnessPosture: 'UNKNOWN', editorialSeparationState: 'EDITORIAL_ONLY', readinessState: 'EVIDENCE_INSUFFICIENT', activationState: 'NOT_AUTHORIZED', correctionState: 'NONE', retirementState: 'ACTIVE', fairHousingBoundary: boundary });
export const GEOGRAPHIC_OBJECT_FIXTURES = {
  niwot: { ...base('GEO-NIWOT', 'Niwot', 'UNINCORPORATED_COMMUNITY'), aliases: [{ value: 'Niwot', kind: 'AMBIGUOUS_ALIAS' as const }], jurisdictionStatus: 'AMBIGUOUS' as const, readinessState: 'AMBIGUOUS_IDENTITY' as const },
  gunbarrel: { ...base('GEO-GUNBARREL', 'Gunbarrel', 'NON_AUTHORITATIVE_EDITORIAL_CONTEXT'), aliases: [{ value: 'Gunbarrel', kind: 'AMBIGUOUS_ALIAS' as const }], jurisdictionStatus: 'AMBIGUOUS' as const, readinessState: 'AMBIGUOUS_IDENTITY' as const },
  tableMesa: { ...base('GEO-TABLE-MESA', 'Table Mesa', 'NEIGHBORHOOD'), aliases: [{ value: 'Table Mesa', kind: 'COMMON_ALIAS' as const }] },
  municipality: base('GEO-MUNICIPALITY-FIXTURE', 'Municipality Fixture', 'MUNICIPALITY'), subdivision: base('GEO-SUBDIVISION-FIXTURE', 'Subdivision Fixture', 'SUBDIVISION'), corridor: base('GEO-CORRIDOR-FIXTURE', 'Corridor Fixture', 'CORRIDOR'), marketArea: base('GEO-MARKET-FIXTURE', 'Market Fixture', 'MARKET_AREA'), editorial: base('GEO-EDITORIAL-FIXTURE', 'Editorial Fixture', 'NON_AUTHORITATIVE_EDITORIAL_CONTEXT'),
} as const;
