export const PROPERTY_RELATIONSHIP_ARCHITECTURE_STATUS = 'IMPLEMENTED_INTERNAL_ARCHITECTURE_ONLY' as const;
export type PropertyGeographicRelationshipType = 'PROPERTY_WITHIN_OBJECT_BOUNDARY' | 'PROPERTY_ASSOCIATED_WITH_MUNICIPALITY' | 'PROPERTY_ASSOCIATED_WITH_SUBDIVISION' | 'PROPERTY_ASSOCIATED_WITH_NEIGHBORHOOD' | 'PROPERTY_CONTEXT_FOR_MARKET_AREA' | 'PROPERTY_NEAR_CORRIDOR' | 'PROVIDER_REPORTED_GEOGRAPHY' | 'EDITORIAL_CONTEXT_REFERENCE' | 'CUSTOMER_SELECTED_CONTEXT';
export type PropertyRelationshipState = 'CANDIDATE' | 'INTERNAL_GOVERNED' | 'VERIFIED_BOUNDARY' | 'DISPUTED' | 'CORRECTION_REQUIRED' | 'BLOCKED' | 'RETIRED';
export type PropertyRelationshipReason = 'PROPERTY_IDENTITY_REQUIRED' | 'OBJECT_IDENTITY_REQUIRED' | 'EVIDENCE_REQUIRED' | 'RIGHTS_REQUIRED' | 'FRESHNESS_REQUIRED' | 'BOUNDARY_AUTHORITY_REQUIRED' | 'GEOMETRY_METHOD_REQUIRED' | 'CONFLICT_REQUIRES_REVIEW' | 'PROVIDER_OBSERVATION_NOT_AUTHORITY' | 'EDITORIAL_OR_CUSTOMER_CONTEXT_NOT_AUTHORITY' | 'RUNTIME_ASSIGNMENT_NOT_AUTHORIZED' | 'PUBLIC_ACTIVATION_NOT_AUTHORIZED' | 'FAIR_HOUSING_USE_NOT_AUTHORIZED';
export type PropertyRelationshipInput = Readonly<{ propertyId: string | null; propertyEffective: 'KNOWN' | 'UNKNOWN'; objectId: string | null; objectType: string | null; relationshipType: PropertyGeographicRelationshipType; evidenceIds: readonly string[]; rights: 'APPROVED' | 'UNKNOWN' | 'INSUFFICIENT'; freshness: 'CURRENT' | 'STALE' | 'UNKNOWN'; boundary: 'CERTIFIED' | 'UNSUPPORTED' | 'CONFLICTING'; geometry: 'VERSIONED_CERTIFIED' | 'LAT_LNG_ONLY' | 'NONE'; provenance: 'CERTIFIED' | 'PROVIDER_REPORTED' | 'EDITORIAL' | 'CUSTOMER_SELECTED' | 'UNKNOWN'; conflict: boolean; professionalVerification: 'COMPLETE' | 'REQUIRED'; correction: 'NONE' | 'REQUIRED' | 'SUPERSEDED'; retired: boolean; requestedActivation: boolean; requestedAssignment: boolean; prohibitedUse: boolean }>;
export type PropertyRelationshipResult = Readonly<{ state: PropertyRelationshipState; visibility: 'ADMIN_ONLY' | 'DATA_INSUFFICIENT' | 'COMPLIANCE_BLOCKED'; activationState: 'NOT_AUTHORIZED'; runtimeAssignment: false; reasons: readonly PropertyRelationshipReason[] }>;
export function evaluatePropertyRelationship(input: PropertyRelationshipInput): PropertyRelationshipResult {
  const reasons: PropertyRelationshipReason[] = [];
  if (!input.propertyId || input.propertyEffective !== 'KNOWN') reasons.push('PROPERTY_IDENTITY_REQUIRED'); if (!input.objectId || !input.objectType) reasons.push('OBJECT_IDENTITY_REQUIRED'); if (!input.evidenceIds.length) reasons.push('EVIDENCE_REQUIRED'); if (input.rights !== 'APPROVED') reasons.push('RIGHTS_REQUIRED'); if (input.freshness !== 'CURRENT') reasons.push('FRESHNESS_REQUIRED');
  const boundaryRelationship = input.relationshipType === 'PROPERTY_WITHIN_OBJECT_BOUNDARY'; if (boundaryRelationship && input.boundary !== 'CERTIFIED') reasons.push('BOUNDARY_AUTHORITY_REQUIRED'); if (boundaryRelationship && input.geometry !== 'VERSIONED_CERTIFIED') reasons.push('GEOMETRY_METHOD_REQUIRED'); if (input.conflict) reasons.push('CONFLICT_REQUIRES_REVIEW');
  if (input.provenance === 'PROVIDER_REPORTED') reasons.push('PROVIDER_OBSERVATION_NOT_AUTHORITY'); if (input.provenance === 'EDITORIAL' || input.provenance === 'CUSTOMER_SELECTED') reasons.push('EDITORIAL_OR_CUSTOMER_CONTEXT_NOT_AUTHORITY'); if (input.requestedAssignment) reasons.push('RUNTIME_ASSIGNMENT_NOT_AUTHORIZED'); if (input.requestedActivation) reasons.push('PUBLIC_ACTIVATION_NOT_AUTHORIZED'); if (input.prohibitedUse) reasons.push('FAIR_HOUSING_USE_NOT_AUTHORIZED');
  const state: PropertyRelationshipState = input.retired ? 'RETIRED' : input.correction === 'SUPERSEDED' ? 'CORRECTION_REQUIRED' : input.conflict ? 'DISPUTED' : reasons.length ? 'BLOCKED' : boundaryRelationship ? 'VERIFIED_BOUNDARY' : 'INTERNAL_GOVERNED'; const visibility = input.prohibitedUse ? 'COMPLIANCE_BLOCKED' : reasons.length ? 'DATA_INSUFFICIENT' : 'ADMIN_ONLY'; return { state, visibility, activationState: 'NOT_AUTHORIZED', runtimeAssignment: false, reasons };
}
