import { NextRequest, NextResponse } from 'next/server';

import { authorizeAdminRequest, isSameOriginAdminRequest } from '@/lib/admin/adminAuth';
import { createStrategySuiteService, StrategySuiteError, type StrategyProfile } from '@/lib/multiDimensionalStrategySuite';
import { buildStrategyBriefFixture, StrategyOutputError } from '@/lib/multiDimensionalStrategyOutputPersistence';
import { createOutputPersistenceService, OutputPersistenceError } from '@/lib/outputPersistenceFoundation';
import { prisma } from '@/lib/prisma';

export const dynamic = 'force-dynamic'; export const revalidate = 0; export const runtime = 'nodejs';
const ROUTE = '/api/agent/strategy-suite'; const HEADERS = { 'Cache-Control': 'private, no-store', Vary: 'Cookie' };
async function subjectFor(request: NextRequest, method: 'GET' | 'POST') { const auth = await authorizeAdminRequest(request, { pathname: ROUTE, method }); return auth.authenticated && auth.identityType === 'HUMAN_AGENT' && auth.role === 'AGENT' && auth.mechanism === 'HUMAN_AGENT_SESSION' && auth.subject && (method === 'GET' || auth.canMutate && isSameOriginAdminRequest(request)) ? auth.subject : null; }
function errorResponse(error: unknown) { if (error instanceof StrategySuiteError || error instanceof StrategyOutputError) return NextResponse.json({ error: error.message, code: error.code }, { status: error.code === 'NOT_FOUND' ? 404 : error.code === 'OWNERSHIP_DENIED' ? 403 : 400, headers: HEADERS }); if (error instanceof OutputPersistenceError) return NextResponse.json({ error: error.message, code: error.code }, { status: error.code === 'OWNERSHIP_DENIED' ? 403 : 400, headers: HEADERS }); return NextResponse.json({ error: 'Strategy Suite is unavailable.', code: 'PERSISTENCE_UNAVAILABLE' }, { status: 503, headers: HEADERS }); }

async function syntheticProperty(label: string) { const normalized = `atlas-synthetic-strategy-${label.toLowerCase().replaceAll(' ', '-')}`; const found = await prisma.canonicalPhysicalProperty.findFirst({ where: { normalizedSitusAddress: normalized } }); return found ?? prisma.canonicalPhysicalProperty.create({ data: { sourceFormattedSitusAddress: `ATLAS SYNTHETIC ${label}`, normalizedSitusAddress: normalized, city: 'Boulder', state: 'CO', postalCode: '80302', identityStatus: 'UNRESOLVED', identityConfidence: 'UNVERIFIED' } }); }
async function syntheticAlternative(profile: StrategyProfile) {
  const [existing, primary, investment] = await Promise.all([syntheticProperty('Existing Primary'), syntheticProperty('New Primary'), syntheticProperty('Investment Property')]);
  const hasInvestment = profile.endsWith('AND_INVESTMENT'); const keeping = profile.startsWith('KEEP_');
  return { analysisKey: 'ATLAS_SYNTHETIC_MULTI_DIMENSIONAL_STRATEGY_V1', analysisTitle: 'ATLAS Synthetic Multi-Dimensional Strategy Certification', analysisPurpose: 'Internal Agent real-estate strategy decision-support certification only.', alternativeKey: `ATLAS_SYNTHETIC_STRATEGY_${profile}`, strategyProfile: profile, additionalLiquidCapitalCents: 18000000, reserveTargetCents: 1500000, review: true,
    existing: { canonicalPropertyId: existing.id, label: 'ATLAS Synthetic Existing Primary', saleProceedsCents: 15000000, currentValueCents: 60000000, debtBalanceCents: 28000000, monthlyDebtPaymentCents: 210000, monthlyRentCents: keeping ? 310000 : 0, vacancyBasisPoints: 500, managementBasisPoints: 800, monthlyTaxesCents: 50000, monthlyInsuranceCents: 18000, monthlyHoaCents: 0, monthlyMaintenanceCents: 16000, monthlyCapexReserveCents: 14000, qualification: 'SYNTHETIC_CERTIFICATION', rentalPermissionStatus: 'NOT_VERIFIED' },
    acquisitionProperties: [
      { canonicalPropertyId: primary.id, role: 'NEW_PRIMARY', label: 'ATLAS Synthetic New Primary', purchasePriceCents: 50000000, downPaymentCents: 10000000, closingCostsCents: 900000, monthlyTaxesCents: 55000, monthlyInsuranceCents: 18000, monthlyHoaCents: 0, monthlyRentCents: 0, vacancyBasisPoints: 0, managementBasisPoints: 0, monthlyMaintenanceCents: 0, monthlyCapexReserveCents: 0, annualRateBasisPoints: 650, loanTermMonths: 360, monthlyMortgageInsuranceCents: 0, qualification: 'SYNTHETIC_CERTIFICATION' },
      ...(hasInvestment ? [{ canonicalPropertyId: investment.id, role: 'INVESTMENT_PROPERTY', label: 'ATLAS Synthetic Investment Property', purchasePriceCents: 40000000, downPaymentCents: 8000000, closingCostsCents: 700000, monthlyTaxesCents: 40000, monthlyInsuranceCents: 16000, monthlyHoaCents: 15000, monthlyRentCents: 320000, vacancyBasisPoints: 500, managementBasisPoints: 800, monthlyMaintenanceCents: 15000, monthlyCapexReserveCents: 12000, annualRateBasisPoints: 675, loanTermMonths: 360, monthlyMortgageInsuranceCents: 0, qualification: 'SYNTHETIC_CERTIFICATION' }] : []),
    ],
  };
}
export async function GET(request: NextRequest) { const subject = await subjectFor(request, 'GET'); if (!subject) return NextResponse.json({ error: 'Agent authentication required.' }, { status: 403, headers: HEADERS }); try { const [analyses, outputs] = await Promise.all([createStrategySuiteService(prisma).listOwned(subject), createOutputPersistenceService(prisma).listOwnedOutputHistory(subject)]); return NextResponse.json({ analyses, outputs }, { headers: HEADERS }); } catch (error) { return errorResponse(error); } }
export async function POST(request: NextRequest) { const subject = await subjectFor(request, 'POST'); if (!subject) return NextResponse.json({ error: 'Agent authentication required.' }, { status: 403, headers: HEADERS }); try { const body = await request.json() as Record<string, unknown>; const service = createStrategySuiteService(prisma); if (body.action === 'CREATE_SYNTHETIC_ALTERNATIVE') { const profile = body.profile as StrategyProfile; const outcome = await service.createAlternative(subject, await syntheticAlternative(profile)); return NextResponse.json(outcome, { status: outcome.created ? 201 : 200, headers: HEADERS }); } if (body.action === 'CLONE_ALTERNATIVE') { return NextResponse.json(await service.cloneAlternative(subject, body.clone), { headers: HEADERS }); } if (body.action === 'UPDATE_RETAINED_RENT') { if (typeof body.alternativeId !== 'string' || typeof body.retainedRentCents !== 'number') throw new StrategySuiteError('INVALID_REQUEST', 'alternativeId and retainedRentCents are required.'); return NextResponse.json(await service.updateDraft(subject, body.alternativeId, body.retainedRentCents), { headers: HEADERS }); } if (body.action === 'RECALCULATE_ALTERNATIVE') { if (typeof body.alternativeId !== 'string') throw new StrategySuiteError('INVALID_REQUEST', 'alternativeId is required.'); return NextResponse.json(await service.recalculate(subject, body.alternativeId), { headers: HEADERS }); } if (body.action === 'REVIEW_ALTERNATIVE') { if (typeof body.alternativeId !== 'string') throw new StrategySuiteError('INVALID_REQUEST', 'alternativeId is required.'); return NextResponse.json(await service.reviewAlternative(subject, body.alternativeId), { headers: HEADERS }); } if (body.action === 'CALCULATE_SENSITIVITY') { if (typeof body.alternativeId !== 'string' || typeof body.rentDeltaCents !== 'number') throw new StrategySuiteError('INVALID_REQUEST', 'alternativeId and rentDeltaCents are required.'); return NextResponse.json(await service.sensitivity(subject, body.alternativeId, body.rentDeltaCents), { headers: HEADERS }); } if (body.action === 'PERSIST_STRATEGY_BRIEF') { if (typeof body.analysisId !== 'string' || !Array.isArray(body.alternativeIds) || body.alternativeIds.some((id) => typeof id !== 'string')) throw new StrategySuiteError('INVALID_REQUEST', 'analysisId and alternativeIds are required.'); const fixture = await buildStrategyBriefFixture(prisma, subject, { analysisId: body.analysisId, alternativeIds: body.alternativeIds as string[] }); const output = await createOutputPersistenceService(prisma).persistReviewedFixture(subject, fixture, 'Multi-Dimensional Strategy Brief reviewed in Agent workspace.'); return NextResponse.json({ output }, { status: output.created ? 201 : 200, headers: HEADERS }); } throw new StrategySuiteError('INVALID_REQUEST', 'Unsupported strategy action.'); } catch (error) { return errorResponse(error); } }
