import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { PRIVATE_SITE_ACCESS_COOKIE, createPrivateSiteAccessSessionValue, getPrivateSiteAccessConfiguration, getPrivateSiteAccessCookieOptions, sanitizePrivateAccessReturnPath, validatePrivateSiteAccessSecret, validatePrivateSiteAccessSessionValue } from '../lib/privateSiteAccess';

const configuration = getPrivateSiteAccessConfiguration({ NODE_ENV: 'production', PROJECT_ATLAS_PRIVATE_ACCESS_SECRET: 'fixture-private-access-secret', PROJECT_ATLAS_PRIVATE_ACCESS_SESSION_VERSION: '7' });
const nowMs = Date.parse('2026-08-22T12:00:00.000Z');
assert.equal(configuration.configurationState, 'ENABLED');
assert.equal(getPrivateSiteAccessConfiguration({ NODE_ENV: 'production' }).configurationState, 'MISSING_SECRET');
assert.equal(await validatePrivateSiteAccessSecret('fixture-private-access-secret', configuration), true);
assert.equal(await validatePrivateSiteAccessSecret('incorrect', configuration), false);
const session = await createPrivateSiteAccessSessionValue(configuration, nowMs);
assert.equal(session.includes('fixture-private-access-secret'), false);
assert.equal(await validatePrivateSiteAccessSessionValue(session, configuration, nowMs + 1), true);
assert.equal(await validatePrivateSiteAccessSessionValue(`${session}x`, configuration, nowMs + 1), false);
assert.equal(await validatePrivateSiteAccessSessionValue(session, configuration, nowMs + 9 * 60 * 60 * 1000), false);
assert.equal(PRIVATE_SITE_ACCESS_COOKIE, 'project_atlas_private_access');
assert.equal(getPrivateSiteAccessCookieOptions(true).httpOnly, true);
assert.equal(getPrivateSiteAccessCookieOptions(true).secure, true);
assert.equal(sanitizePrivateAccessReturnPath('/properties/one?from=search'), '/properties/one?from=search');
assert.equal(sanitizePrivateAccessReturnPath('https://example.com'), '/');
assert.equal(sanitizePrivateAccessReturnPath('//example.com'), '/');
assert.equal(sanitizePrivateAccessReturnPath('/private-access?next=/admin'), '/');
const middleware = readFileSync('middleware.ts', 'utf8');
const accessRoute = readFileSync('app/private-access/login/route.ts', 'utf8');
const rootLayout = readFileSync('app/layout.tsx', 'utf8');
const robots = readFileSync('app/robots.ts', 'utf8');
assert.match(middleware, /matcher: \['\/\(\(\?!_next\/\)\.\*\)'/);
assert.match(middleware, /Private access required/);
assert.match(middleware, /Private development access is unavailable/);
assert.match(middleware, /\/agent\/prepare\/listing/);
assert.match(middleware, /isAdminProtectedRoute/);
assert.match(middleware, /Cache-Control', 'private, no-store/);
assert.match(middleware, /X-Robots-Tag', 'noindex, nofollow/);
assert.match(accessRoute, /candidate\.length > 512/);
assert.match(accessRoute, /isSameOriginPrivateAccessRequest/);
assert.match(rootLayout, /x-project-atlas-private-gate/);
assert.match(rootLayout, /privateGate \? children : <ApplicationShell>/);
assert.match(robots, /disallow: '\/'/);
console.log('TEMPORARY_PRIVATE_SITE_ACCESS_GATE_CHECK: PASS');
