import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';

import { calculateStrategyAlternative, MULTI_DIMENSIONAL_STRATEGY_BRIEF_V1, validateStrategyRequest } from '../lib/multiDimensionalStrategySuite';

function assert(condition: unknown, message: string): asserts condition { if (!condition) throw new Error(message); }
const root = resolve(import.meta.dirname, '..');
const fixture = (profile: string) => ({ analysisKey: 'check', analysisTitle: 'check', analysisPurpose: 'check', alternativeKey: profile, strategyProfile: profile, additionalLiquidCapitalCents: 18_000_000, reserveTargetCents: 1_500_000, supersedesAlternativeId: null, review: false, existing: { canonicalPropertyId: 'existing', label: 'Existing', saleProceedsCents: 15_000_000, currentValueCents: 60_000_000, debtBalanceCents: 28_000_000, monthlyDebtPaymentCents: 210_000, monthlyRentCents: profile.startsWith('KEEP_') ? 310_000 : 0, vacancyBasisPoints: 500, managementBasisPoints: 800, monthlyTaxesCents: 50_000, monthlyInsuranceCents: 18_000, monthlyHoaCents: 0, monthlyMaintenanceCents: 16_000, monthlyCapexReserveCents: 14_000, qualification: 'SYNTHETIC_CERTIFICATION', rentalPermissionStatus: 'NOT_VERIFIED' }, acquisitionProperties: [{ canonicalPropertyId: 'primary', role: 'NEW_PRIMARY', label: 'Primary', purchasePriceCents: 50_000_000, downPaymentCents: 10_000_000, closingCostsCents: 900_000, monthlyTaxesCents: 55_000, monthlyInsuranceCents: 18_000, monthlyHoaCents: 0, monthlyRentCents: 0, vacancyBasisPoints: 0, managementBasisPoints: 0, monthlyMaintenanceCents: 0, monthlyCapexReserveCents: 0, annualRateBasisPoints: 650, loanTermMonths: 360, monthlyMortgageInsuranceCents: 0, qualification: 'SYNTHETIC_CERTIFICATION' }, ...(profile.endsWith('AND_INVESTMENT') ? [{ canonicalPropertyId: 'investment', role: 'INVESTMENT_PROPERTY', label: 'Investment', purchasePriceCents: 40_000_000, downPaymentCents: 8_000_000, closingCostsCents: 700_000, monthlyTaxesCents: 40_000, monthlyInsuranceCents: 16_000, monthlyHoaCents: 15_000, monthlyRentCents: 320_000, vacancyBasisPoints: 500, managementBasisPoints: 800, monthlyMaintenanceCents: 15_000, monthlyCapexReserveCents: 12_000, annualRateBasisPoints: 675, loanTermMonths: 360, monthlyMortgageInsuranceCents: 0, qualification: 'SYNTHETIC_CERTIFICATION' }] : [])] });

const sell = calculateStrategyAlternative(validateStrategyRequest(fixture('SELL_EXISTING_BUY_PRIMARY')));
const keep = calculateStrategyAlternative(validateStrategyRequest(fixture('KEEP_EXISTING_CONVERT_TO_RENTAL_AND_BUY_PRIMARY')));
assert(sell.availableLiquidCapitalCents === 33_000_000, 'Sell liquidity must include qualified sale proceeds plus additional liquid capital.');
assert(keep.availableLiquidCapitalCents === 18_000_000, 'Retained equity must not enter liquid acquisition capital.');
assert(keep.netRetainedPropertyEquityCents === 32_000_000 && keep.retainedProperty?.rentalPermissionStatus === 'NOT_VERIFIED', 'Keep strategy must preserve separate retained equity and qualification.');
assert(calculateStrategyAlternative(validateStrategyRequest(fixture('SELL_EXISTING_BUY_PRIMARY'))).remainingLiquidityCents === sell.remainingLiquidityCents, 'Strategy calculation must be deterministic.');
assert(calculateStrategyAlternative(validateStrategyRequest({ ...fixture('KEEP_EXISTING_CONVERT_TO_RENTAL_AND_BUY_PRIMARY'), existing: { ...fixture('KEEP_EXISTING_CONVERT_TO_RENTAL_AND_BUY_PRIMARY').existing, monthlyRentCents: 330_000 } })).householdMonthlyPropertyCashRequirementCents < keep.householdMonthlyPropertyCashRequirementCents, 'Sensitivity must change only the calculated scenario.');
for (const profile of ['SELL_EXISTING_BUY_PRIMARY_AND_INVESTMENT', 'KEEP_EXISTING_CONVERT_TO_RENTAL_AND_BUY_PRIMARY_AND_INVESTMENT']) assert(validateStrategyRequest(fixture(profile)).acquisitionProperties.length === 2, `Profile ${profile} must include the investment component.`);
let rejectedConflict = false; try { validateStrategyRequest({ ...fixture('SELL_EXISTING_BUY_PRIMARY'), acquisitionProperties: [{ ...fixture('SELL_EXISTING_BUY_PRIMARY').acquisitionProperties[0], canonicalPropertyId: 'existing' }] }); } catch { rejectedConflict = true; } assert(rejectedConflict, 'Conflicting physical-property roles must be rejected.');
const [schema, migration, route, output, workspace] = await Promise.all(['prisma/schema.prisma', 'prisma/migrations/20260901000000_add_multi_dimensional_strategy_suite/migration.sql', 'app/api/agent/strategy-suite/route.ts', 'lib/multiDimensionalStrategyOutputPersistence.ts', 'components/agent/MultiDimensionalStrategyWorkspace.tsx'].map((path) => readFile(resolve(root, path), 'utf8')));
for (const token of ['model StrategyAnalysis', 'model StrategyAlternative', 'model StrategyAlternativeResult', 'model StrategyPropertyRole', 'model StrategyAlternativeDependency', 'model StrategyAlternativeAuditEvent']) assert(schema.includes(token), `Schema lacks ${token}.`);
for (const token of ['StrategyAlternativeResult_append_only', 'StrategyAlternative_reviewed_immutable']) assert(migration.includes(token), `Migration lacks immutable protection ${token}.`);
for (const token of ['CREATE_SYNTHETIC_ALTERNATIVE', 'CLONE_ALTERNATIVE', 'UPDATE_RETAINED_RENT', 'RECALCULATE_ALTERNATIVE', 'REVIEW_ALTERNATIVE', 'CALCULATE_SENSITIVITY', 'PERSIST_STRATEGY_BRIEF']) assert(route.includes(token), `Agent route lacks ${token}.`);
assert(output.includes(MULTI_DIMENSIONAL_STRATEGY_BRIEF_V1) && route.includes('persistReviewedFixture'), 'Strategy Brief must reuse shared immutable OutputVersion persistence.');
for (const token of ['SELL_EXISTING_BUY_PRIMARY', 'SELL_EXISTING_BUY_PRIMARY_AND_INVESTMENT', 'KEEP_EXISTING_CONVERT_TO_RENTAL_AND_BUY_PRIMARY', 'KEEP_EXISTING_CONVERT_TO_RENTAL_AND_BUY_PRIMARY_AND_INVESTMENT', 'No lender, tax, legal']) assert(workspace.includes(token), `Agent workspace lacks ${token}.`);
console.log('MULTI_DIMENSIONAL_STRATEGY_SUITE_V1_CHECK: PASS');
