'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { BarChart3, CopyPlus, FileCheck2, FlaskConical, RefreshCw, ShieldAlert } from 'lucide-react';

type Json = Record<string, unknown>;
type Projection = Json & { id: string; projectionKey: string; lifecycleState: string; inputSnapshot: Json; results: Json[] };
type Analysis = Json & { id: string; title: string; projections: Projection[] };
const money = (value: unknown) => typeof value === 'number' ? new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(value / 100) : 'N/A';
const percent = (value: unknown) => typeof value === 'number' ? `${(value / 100).toFixed(2)}%` : 'N/A';

export default function AdvancedInvestmentReturnWorkspace() {
  const [analyses, setAnalyses] = useState<Analysis[]>([]); const [outputs, setOutputs] = useState<Json[]>([]); const [status, setStatus] = useState(''); const [busy, setBusy] = useState(false); const [sensitivity, setSensitivity] = useState<Json | null>(null);
  const load = useCallback(async () => { const response = await fetch('/api/agent/advanced-investment-return', { cache: 'no-store' }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Advanced Return Analysis is unavailable.'); setAnalyses(body.analyses); setOutputs(body.outputs); }, []);
  useEffect(() => { const timer = window.setTimeout(() => { void load().catch((error: Error) => setStatus(error.message)); }, 0); return () => window.clearTimeout(timer); }, [load]);
  const run = useCallback(async (payload: Json) => { setBusy(true); try { const response = await fetch('/api/agent/advanced-investment-return', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Advanced Return action failed.'); setStatus(body.output ? `Immutable output ${body.output.versionOrdinal} is available.` : 'Advanced Return analysis updated.'); if (body.horizons) setSensitivity(body); await load(); return body; } catch (error) { setStatus(error instanceof Error ? error.message : 'Advanced Return action failed.'); return null; } finally { setBusy(false); } }, [load]);
  const projections = useMemo(() => analyses.flatMap((analysis) => analysis.projections), [analyses]);
  return <main className="mx-auto max-w-6xl px-5 py-8 sm:px-8 lg:px-12" data-testid="advanced-investment-return-workspace">
    <header className="max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-cyan-100/70">Project Atlas / V2</p><h1 className="mt-2 text-2xl font-semibold text-white">Advanced Investment Return</h1><p className="mt-2 text-sm leading-6 text-slate-300">Holding-period scenarios, capital trajectories, and immutable Agent-reviewed decision support.</p></header>
    {status && <p className="mt-4 border border-cyan-100/20 bg-cyan-100/[0.06] px-4 py-3 text-sm text-cyan-50" role="status">{status}</p>}
    <section className="mt-6 border border-amber-100/20 bg-amber-100/[0.04] p-5"><div className="flex gap-3"><ShieldAlert size={18} className="shrink-0 text-amber-100"/><p className="text-sm leading-6 text-slate-300">Pre-tax modeled decision support only. No recommendation, client delivery, tax analysis, lender action, financial-account connection, secure document, CRM, MLS, Compass, or external action is available.</p></div></section>
    <section className="mt-6 border border-white/10 bg-white/[0.035] p-5"><h2 className="text-sm font-semibold">Synthetic certified sources</h2><div className="mt-4 flex flex-wrap gap-2"><button disabled={busy} onClick={() => void run({ action: 'CREATE_SYNTHETIC_BASE' })} className="inline-flex min-h-10 items-center gap-2 border border-cyan-100/35 px-3 text-sm font-semibold text-cyan-50 disabled:opacity-50"><BarChart3 size={15}/>Create single investment</button><button disabled={busy} onClick={() => void run({ action: 'CREATE_SYNTHETIC_STRATEGY', profile: 'SELL_EXISTING_BUY_PRIMARY_AND_INVESTMENT' })} className="inline-flex min-h-10 items-center gap-2 border border-cyan-100/35 px-3 text-sm font-semibold text-cyan-50 disabled:opacity-50"><BarChart3 size={15}/>Create Strategy B</button><button disabled={busy} onClick={() => void run({ action: 'CREATE_SYNTHETIC_STRATEGY', profile: 'KEEP_EXISTING_CONVERT_TO_RENTAL_AND_BUY_PRIMARY' })} className="inline-flex min-h-10 items-center gap-2 border border-cyan-100/35 px-3 text-sm font-semibold text-cyan-50 disabled:opacity-50"><BarChart3 size={15}/>Create Strategy C</button></div></section>
    {sensitivity && <section className="mt-6 border border-white/10 bg-white/[0.035] p-5"><h2 className="text-sm font-semibold">Sensitivity preview</h2><HorizonTable result={sensitivity}/><p className="mt-3 text-xs text-slate-400">Preview only. No persisted projection was changed.</p></section>}
    <section className="mt-6 grid gap-4 xl:grid-cols-2">{projections.map((projection) => <ProjectionCard key={projection.id} projection={projection} busy={busy} onRun={run}/>)}</section>
    <section className="mt-6 border border-white/10 bg-white/[0.035] p-5"><h2 className="text-sm font-semibold">Reviewed output history</h2>{outputs.length ? <div className="mt-3 space-y-2">{outputs.filter((output) => String(output.sourceVersionRef || '').startsWith('ADVANCED_INVESTMENT_RETURN_ANALYSIS_V2')).map((output) => <p key={String(output.id)} className="text-sm text-slate-300">{String(output.displayVersion)} · immutable version {String(output.versionOrdinal)}</p>)}</div> : <p className="mt-3 text-sm text-slate-400">No Advanced Return output has been persisted.</p>}</section>
  </main>;
}

function ProjectionCard({ projection, busy, onRun }: { projection: Projection; busy: boolean; onRun: (payload: Json) => Promise<Json | null> }) {
  const input = projection.inputSnapshot; const result = projection.results[0]?.resultSnapshot as Json | undefined; const editable = projection.lifecycleState !== 'AGENT_REVIEWED'; const [appreciation, setAppreciation] = useState(String(input.appreciationBasisPoints ?? 300));
  const cloneKey = `${projection.projectionKey}-SUCCESSOR`;
  return <article className="border border-white/10 bg-white/[0.035] p-5" data-testid={`advanced-return-projection-${projection.id}`}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.1em] text-cyan-100/70">{String(projection.analysisProfile || '').replaceAll('_', ' ')}</p><h2 className="mt-1 font-semibold">{projection.projectionKey}</h2><p className="mt-1 text-xs text-slate-400">{projection.lifecycleState.replaceAll('_', ' ')}</p></div><BarChart3 size={18} className="text-cyan-100"/></div>
    <dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><Metric label="Horizons" value={Array.isArray(input.horizonMonths) ? input.horizonMonths.map((month) => `${Number(month) / 12}y`).join(', ') : 'N/A'}/><Metric label="Disposition" value={String(input.disposition || '').replaceAll('_', ' ')}/><Metric label="Appreciation" value={percent(input.appreciationBasisPoints)}/><Metric label="Rent growth" value={percent(input.rentGrowthBasisPoints)}/><Metric label="Expense growth" value={percent(input.expenseGrowthBasisPoints)}/><Metric label="Discount rate" value={percent(input.discountRateBasisPoints)}/></dl>
    {result ? <HorizonTable result={result}/> : <p className="mt-4 text-sm text-amber-100">Current assumptions need recalculation before review.</p>}
    <div className="mt-4 flex flex-wrap gap-2 border-t border-white/10 pt-3"><button disabled={busy} onClick={() => void onRun({ action: 'CLONE_PROJECTION', sourceProjectionId: projection.id, projectionKey: cloneKey })} className="inline-flex min-h-9 items-center gap-1 border border-white/20 px-2 text-xs text-slate-200 disabled:opacity-50"><CopyPlus size={13}/>Clone</button><button disabled={busy} onClick={() => void onRun({ action: 'SENSITIVITY', projectionId: projection.id, assumptions: { appreciationBasisPoints: -200, rentGrowthBasisPoints: 0, expenseGrowthBasisPoints: 450, dispositionCostBasisPoints: 800, discountRateBasisPoints: 1000 } })} className="inline-flex min-h-9 items-center gap-1 border border-cyan-100/30 px-2 text-xs text-cyan-50 disabled:opacity-50"><FlaskConical size={13}/>Downside</button>{editable && <><input aria-label="Annual appreciation basis points" value={appreciation} onChange={(event) => setAppreciation(event.target.value)} className="min-h-9 w-24 border border-white/20 bg-black/20 px-2 text-xs"/><button disabled={busy} onClick={() => void onRun({ action: 'UPDATE_ASSUMPTIONS', projectionId: projection.id, assumptions: { appreciationBasisPoints: Number(appreciation) } })} className="min-h-9 border border-white/20 px-2 text-xs disabled:opacity-50">Update</button><button disabled={busy} onClick={() => void onRun({ action: 'RECALCULATE', projectionId: projection.id })} className="inline-flex min-h-9 items-center gap-1 border border-white/20 px-2 text-xs disabled:opacity-50"><RefreshCw size={13}/>Recalculate</button><button disabled={busy} onClick={() => void onRun({ action: 'REVIEW', projectionId: projection.id })} className="min-h-9 border border-emerald-200/35 px-2 text-xs text-emerald-50 disabled:opacity-50">Review</button></>}<button disabled={busy || projection.lifecycleState !== 'AGENT_REVIEWED'} onClick={() => void onRun({ action: 'PERSIST_OUTPUT', projectionId: projection.id })} className="inline-flex min-h-9 items-center gap-1 border border-emerald-200/35 px-2 text-xs text-emerald-50 disabled:opacity-50"><FileCheck2 size={13}/>Persist output</button></div>
  </article>;
}

function HorizonTable({ result }: { result: Json }) { const horizons = Array.isArray(result.horizons) ? result.horizons as Json[] : []; if (!horizons.length) return null; return <div className="mt-5 overflow-x-auto"><table className="min-w-full text-left text-xs"><thead className="text-slate-500"><tr><th className="pb-2 pr-3">Horizon</th><th className="pb-2 pr-3">Value</th><th className="pb-2 pr-3">Equity</th><th className="pb-2 pr-3">Cash flow</th><th className="pb-2 pr-3">Exit proceeds</th><th className="pb-2 pr-3">IRR</th><th className="pb-2">NPV</th></tr></thead><tbody>{horizons.map((horizon) => <tr key={String(horizon.month)} className="border-t border-white/10 text-slate-300"><td className="py-2 pr-3">{Number(horizon.month) / 12}y</td><td className="py-2 pr-3">{money((horizon.propertyPeriods as Json[] | undefined)?.reduce((total, property) => total + Number(property.modeledValueCents || 0), 0))}</td><td className="py-2 pr-3">{money(horizon.modeledGrossEquityCents)}</td><td className="py-2 pr-3">{money(horizon.cumulativeCashFlowCents)}</td><td className="py-2 pr-3">{money(horizon.dispositionProceedsCents)}</td><td className="py-2 pr-3">{percent(horizon.propertyLevelIrrAnnualBasisPoints)}</td><td className="py-2">{money(horizon.propertyLevelNpvCents)}</td></tr>)}</tbody></table></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 font-semibold text-slate-200">{value}</dd></div>; }
