import { ClipboardCheck, CircleAlert, CheckCircle2 } from 'lucide-react';

import { AtlasButton, AtlasEmptyState, AtlasField, AtlasInformationClassLabel, AtlasNotice, AtlasStatusLabel, AtlasSurface } from '@/components/design-system/AtlasDesignSystem';
import styles from './ClientCaseReadinessVisualFixture.module.css';

export function ClientCaseReadinessVisualFixture() {
  return (
    <main className={`atlas-ds-root atlas-ds-shell-agent ${styles.fixture}`} data-testid="client-case-readiness-visual-fixture">
      <div className="atlas-ds-canvas">
        <header className={styles.header}><div><p className="atlas-ds-label">Project Atlas internal certification fixture</p><h1 className="atlas-ds-page-title">Client Case Readiness</h1><p>Static synthetic interface only. No Client Case, scenario, capability result, request, or record is accessed or created.</p></div><AtlasInformationClassLabel informationClass="system-status" label="Synthetic visual fixture" /></header>
        <AtlasSurface className={styles.panel} material="glass"><div className={styles.panelHeading}><div><h2 className="atlas-ds-major-section">Select context</h2><p className="atlas-ds-metadata">Inspect the readiness workflow hierarchy, labels, controls, and keyboard focus.</p></div><AtlasStatusLabel status="pending" label="Selection required" /></div><div className={styles.selectionGrid}><AtlasField htmlFor="fixture-case" label="Client Case"><select className="atlas-ds-select" defaultValue="case"><option value="case">ATLAS Synthetic Client Case</option></select></AtlasField><AtlasField htmlFor="fixture-context" label="Context"><select className="atlas-ds-select" defaultValue="baseline"><option value="baseline">Canonical baseline</option><option value="scenario">Synthetic scenario (current version)</option></select></AtlasField><AtlasField htmlFor="fixture-capability" label="Admitted capability"><select className="atlas-ds-select" defaultValue=""><option value="">Select capability</option><option value="financial">Financial Strategy</option><option value="buyer">Buyer Decision</option><option value="market">Market Intelligence</option></select></AtlasField></div><AtlasButton tone="primary"><ClipboardCheck aria-hidden="true" size={16} />Check readiness</AtlasButton></AtlasSurface>
        <AtlasEmptyState className={styles.empty} title="No active scenarios"><p>Canonical baseline remains available. This static message must remain readable on narrow screens.</p></AtlasEmptyState>
        <section className={styles.result}><div className={styles.panelHeading}><div><p className="atlas-ds-label">Synthetic result</p><h2 className="atlas-ds-major-section">Readiness result</h2></div><AtlasStatusLabel status="complete" label="Comprehensive ready" /></div><AtlasNotice title="Comprehensive ready" tone="success">All synthetic required readiness conditions are shown as satisfied for visual comparison only.</AtlasNotice><div className={styles.resultGrid}><AtlasSurface material="data"><h3 className="atlas-ds-panel-title">Context summary</h3><dl><div><dt>Client Case</dt><dd>ATLAS Synthetic Client Case</dd></div><div><dt>Context</dt><dd>Canonical baseline</dd></div><div><dt>Ruleset</dt><dd>Effective Context V1</dd></div></dl></AtlasSurface><AtlasSurface material="reading"><h3 className="atlas-ds-panel-title">Requirement detail</h3><table><caption className="sr-only">Synthetic readiness requirements</caption><thead><tr><th>Requirement</th><th>Level</th><th>State</th></tr></thead><tbody><tr><td>Target cities</td><td>Preliminary required</td><td>Satisfied</td></tr><tr><td>Purchase price range</td><td>Comprehensive required</td><td>Satisfied</td></tr></tbody></table></AtlasSurface></div><div className={styles.noticeGrid}><AtlasSurface material="data"><CircleAlert aria-hidden="true" size={18} /><h3 className="atlas-ds-panel-title">Helpful missing</h3><p>Minimum bedrooms</p></AtlasSurface><AtlasSurface material="data"><CheckCircle2 aria-hidden="true" size={18} /><h3 className="atlas-ds-panel-title">No limitations</h3><p>No synthetic limitation is present.</p></AtlasSurface></div></section>
      </div>
    </main>
  );
}
