'use client';

import { ChevronDown, CircleAlert, History, Pencil, Plus, Save } from 'lucide-react';
import { useState } from 'react';

import { AtlasButton, AtlasEmptyState, AtlasField, AtlasInformationClassLabel, AtlasNotice, AtlasSurface } from '@/components/design-system/AtlasDesignSystem';
import informationStyles from './ClientCaseInformationWorkspace.module.css';
import styles from './ClientFinancialPositionWorkspace.module.css';

export function ClientFinancialPositionVisualFixture() {
  const [draft, setDraft] = useState(false);
  const [history, setHistory] = useState(false);
  return <main className={`atlas-ds-root atlas-ds-shell-agent ${styles.workspace}`} data-testid="client-financial-position-visual-fixture"><div className={`atlas-ds-canvas ${informationStyles.page}`}><div className={informationStyles.container}>
    <header className={styles.heading}><div><p className={styles.eyebrow}>Project Atlas internal certification fixture</p><h1 className="atlas-ds-page-title">Financial Position</h1><p className={styles.copy}>Static synthetic interface only. No Client, financial record, governed source, Property, Evidence, Professional Input, or request is accessed or created.</p></div><AtlasInformationClassLabel informationClass="system-status" label="Synthetic visual fixture" /></header>
    <AtlasEmptyState title="No financial information entered"><p>Financial information is optional. This empty state does not imply a readiness judgment.</p><AtlasButton onClick={() => setDraft(true)}><Plus aria-hidden="true" size={16} />Add financial information</AtlasButton></AtlasEmptyState>
    <div className={styles.overview}><AtlasSurface material="data"><span>Financial Position</span><strong>Available</strong></AtlasSurface><AtlasSurface material="data"><span>Resources</span><strong>2 records</strong></AtlasSurface><AtlasSurface material="data"><span>Income</span><strong>1 record</strong></AtlasSurface><AtlasSurface material="data"><span>Review attention</span><strong>1 recommended</strong></AtlasSurface></div>
    {draft ? <AtlasSurface className={styles.draft} material="floating"><div className={styles.draftHeading}><div><p className={styles.eyebrow}>Add financial information</p><h2 className="atlas-ds-major-section">Resource / available funds</h2></div><AtlasButton aria-label="Close draft" tone="ghost" onClick={() => setDraft(false)}>Close</AtlasButton></div><div className={styles.fields}><AtlasField htmlFor="fixture-category" label="Category"><select className={styles.select} id="fixture-category" defaultValue="CASH"><option value="CASH">Cash</option><option value="LIQUID_INVESTMENT">Liquid investment</option></select></AtlasField><AtlasField htmlFor="fixture-label" label="Label"><input className={styles.input} id="fixture-label" defaultValue="Reserve funds" /></AtlasField><AtlasField htmlFor="fixture-participant" label="Applies to"><select className={styles.select} id="fixture-participant"><option>Joint / Client Case</option><option>Jordan Avery</option></select></AtlasField><AtlasField htmlFor="fixture-value" label="Current value"><input className={styles.input} id="fixture-value" inputMode="decimal" placeholder="0.00" /></AtlasField><AtlasField htmlFor="fixture-available" label="Available for real-estate purposes"><input className={styles.input} id="fixture-available" inputMode="decimal" placeholder="0.00" /></AtlasField><AtlasField htmlFor="fixture-asof" label="As of"><input className={styles.input} id="fixture-asof" type="date" /></AtlasField></div><details className={styles.advanced}><summary>Source and timing</summary><div className={styles.fields}><AtlasField htmlFor="fixture-source" label="Source posture"><select className={styles.select} id="fixture-source"><option>Client stated</option><option>Document supported</option></select></AtlasField><AtlasField htmlFor="fixture-governed" label="Associated governed source"><select className={styles.select} id="fixture-governed"><option>No governed source selected</option><option>Document supported · lender qualification</option></select></AtlasField></div></details><div className={styles.draftActions}><AtlasButton><Save aria-hidden="true" size={16} />Save</AtlasButton><AtlasButton tone="secondary" onClick={() => setDraft(false)}>Cancel</AtlasButton></div></AtlasSurface> : null}
    <section className={styles.domain}><div className={styles.domainHeading}><div><h2 className="atlas-ds-major-section">Resources</h2><p>2 current records</p></div><AtlasButton tone="secondary" onClick={() => setDraft(true)}><Plus aria-hidden="true" size={16} />Add</AtlasButton></div><div className={styles.recordList}><AtlasSurface className={styles.record} material="glass"><div className={styles.recordHeading}><div><p className={styles.category}>Liquid investment</p><h3>Joint reserve account</h3><p>Joint / Client Case</p></div><span className={styles.review}>Review recommended</span></div><dl className={styles.values}><div><dt>Current value</dt><dd>$420,000</dd></div><div><dt>Available for real-estate purposes</dt><dd>$300,000</dd></div></dl><div className={styles.metadata}><span>As of Sep 12, 2026</span><span>Client stated</span><span>Client confirmed</span></div><div className={styles.recordActions}><AtlasButton tone="secondary" onClick={() => setDraft(true)}><Pencil aria-hidden="true" size={16} />Update</AtlasButton><AtlasButton aria-expanded={history} tone="ghost" onClick={() => setHistory((value) => !value)}><History aria-hidden="true" size={16} />{history ? 'Hide history' : 'View history'}</AtlasButton></div>{history ? <div className={styles.history}><div><strong>Correction</strong><span>As of Sep 1, 2026 · Client stated · Unverified</span></div></div> : null}</AtlasSurface></div></section>
    <section className={styles.domain}><div className={styles.domainHeading}><div><h2 className="atlas-ds-major-section">Lender qualification</h2><p>1 current record</p></div><AtlasButton tone="secondary"><Plus aria-hidden="true" size={16} />Add</AtlasButton></div><AtlasSurface className={styles.record} material="glass"><div className={styles.recordHeading}><div><p className={styles.category}>Preapproval</p><h3>Regional lender preapproval</h3><p>Joint / Client Case</p></div><span className={styles.expired}>Expired</span></div><dl className={styles.values}><div><dt>Maximum loan</dt><dd>$720,000</dd></div><div><dt>Maximum purchase</dt><dd>$900,000</dd></div><div><dt>Quoted rate</dt><dd>6.50%</dd></div></dl><AtlasNotice title="Lender fact" tone="information">This information is supplied by its lender/source and is not an Atlas affordability recommendation.</AtlasNotice></AtlasSurface></section>
    <section className={styles.domain}><div className={styles.domainHeading}><div><h2 className="atlas-ds-major-section">Source selection</h2><p>Explicit Client Case governed sources only</p></div><ChevronDown aria-hidden="true" size={18} /></div><AtlasNotice title="No eligible source is associated" tone="attention"><CircleAlert aria-hidden="true" size={16} /><p>The selector is a valid empty state and never falls back to owner-wide Evidence or Professional Input.</p></AtlasNotice></section>
  </div></div></main>;
}
