import { ChevronDown, Link2, Plus, X } from 'lucide-react';

import { AtlasButton, AtlasInformationClassLabel, AtlasStatusLabel, AtlasSurface } from '@/components/design-system/AtlasDesignSystem';
import styles from './ClientObjectivePropertyRelationshipVisualFixture.module.css';

const complexObjectives = [
  { title: 'Sell: Current residence', properties: ['2810 Pine Street · Property being sold'] },
  { title: 'Buy: Replacement primary home', properties: ['455 Canyon Road · Property being considered', '1920 Maple Avenue · Property being considered'] },
  { title: 'Buy: Mountain residence', properties: ['660 Ridge Lane · Property being considered'] },
  { title: 'Invest: Long-term acquisition', properties: ['1920 Maple Avenue · Property being considered', '77 Pearl Street · Property being considered'] },
] as const;

export function ClientObjectivePropertyRelationshipVisualFixture() {
  return <main className={`atlas-ds-root atlas-ds-shell-agent ${styles.fixture}`} data-testid="client-objective-property-relationship-visual-fixture"><div className="atlas-ds-canvas">
    <header className={styles.header}><div><p className="atlas-ds-label">Project Atlas internal certification fixture</p><h1 className="atlas-ds-page-title">Objective Property Workflow</h1><p>Static synthetic interface only. It does not load or alter Client Cases, Properties, Objectives, or relationship records.</p></div><AtlasInformationClassLabel informationClass="system-status" label="Synthetic visual fixture" /></header>
    <div className={styles.grid}>
      <AtlasSurface className={styles.case} material="glass"><div className={styles.heading}><div><p className={styles.kicker}>Simple Client</p><h2 className="atlas-ds-panel-title">Sell: Current residence</h2></div><AtlasStatusLabel label="Current" status="active" /></div><div className={styles.current}><strong>2810 Pine Street</strong><span>Boulder, CO · Property being sold</span><div><AtlasButton tone="ghost">View Property</AtlasButton><AtlasButton tone="ghost">End relationship</AtlasButton></div></div><button className={styles.history} type="button">Relationship history <ChevronDown aria-hidden="true" size={16} /></button></AtlasSurface>
      <AtlasSurface className={styles.case} material="glass"><div className={styles.heading}><div><p className={styles.kicker}>Valid empty state</p><h2 className="atlas-ds-panel-title">Buy: Relocation search</h2></div><AtlasStatusLabel label="Current" status="active" /></div><p className={styles.empty}>No Properties are currently connected to this Objective.</p><AtlasButton tone="secondary"><Plus aria-hidden="true" size={16} />Add Property</AtlasButton></AtlasSurface>
      <AtlasSurface className={styles.case} material="glass"><div className={styles.heading}><div><p className={styles.kicker}>Expanded link control</p><h2 className="atlas-ds-panel-title">Invest: Long-term acquisition</h2></div><AtlasStatusLabel label="Current" status="active" /></div><div className={styles.linkForm}><label>Client Property<select defaultValue=""><option value="">Select a Client Property</option><option>77 Pearl Street · Boulder, CO</option></select></label><fieldset><legend>Relationship meaning</legend><label><input defaultChecked name="fixture-role" type="radio" />Property being considered</label><label><input name="fixture-role" type="radio" />Property being sold</label></fieldset><div><AtlasButton tone="ghost"><X aria-hidden="true" size={16} />Clear selection</AtlasButton><AtlasButton><Link2 aria-hidden="true" size={16} />Confirm Property</AtlasButton></div></div></AtlasSurface>
      <AtlasSurface className={styles.case} material="glass"><div className={styles.heading}><div><p className={styles.kicker}>Property-side context</p><h2 className="atlas-ds-panel-title">1920 Maple Avenue</h2></div><AtlasStatusLabel label="Client Property" status="active" /></div><p className={styles.propertyRole}>Current Objective relationships</p><ul className={styles.objectiveList}><li><span><strong>Buy: Replacement primary home</strong><small>Property being considered</small></span><a href="#fixture">Open Objective</a></li><li><span><strong>Invest: Long-term acquisition</strong><small>Property being considered</small></span><a href="#fixture">Open Objective</a></li></ul></AtlasSurface>
    </div>
    <AtlasSurface className={styles.complex} material="floating"><div className={styles.heading}><div><p className={styles.kicker}>Complex Client</p><h2 className="atlas-ds-panel-title">Current Objectives</h2></div><span className={styles.count}>4 Objectives</span></div><div className={styles.objectiveGrid}>{complexObjectives.map((objective) => <section key={objective.title}><h3>{objective.title}</h3>{objective.properties.map((property) => <p key={property}>{property}</p>)}</section>)}</div><div className={styles.endState}><strong>End relationship?</strong><span>This ends the Objective relationship. History remains, and the Property stays in the Client Case.</span><AtlasButton tone="ghost">Cancel</AtlasButton><AtlasButton tone="secondary">Confirm End</AtlasButton></div><button aria-expanded="true" className={styles.history} type="button">Relationship history <ChevronDown aria-hidden="true" size={16} /></button><p className={styles.past}>311 Walnut Street · Property being considered · linked Mar 3, 2026 · ended Apr 18, 2026</p></AtlasSurface>
  </div></main>;
}
