'use client';

import { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, CopyPlus, FileCheck2, FlaskConical, ShieldAlert, TrendingUp } from 'lucide-react';

type PropertyInput = Record<string, unknown> & { role: string; label: string; qualification: string };
type Scenario = { id: string; scenarioKey: string; versionOrdinal: number; lifecycleState: string; inputSnapshot: { properties?: PropertyInput[] }; result?: { id: string; resultSnapshot: Record<string, unknown>; resultFingerprint: string } | null; supersedesScenarioId?: string | null };
type Analysis = { id: string; title: string; purpose: string; scenarios: Scenario[] };
type Output = { id: string; displayVersion: string; versionOrdinal: number; contentFingerprint: string; created: boolean };
type Sensitivity = { scenarioKey: string; low?: Record<string, unknown>; high?: Record<string, unknown> };

const money = (value: unknown) => typeof value === 'number' ? new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(value / 100) : 'Not applicable';
const percent = (value: unknown) => typeof value === 'number' ? `${(value / 100).toFixed(2)}%` : 'Not applicable';

function certificationScenario(key: 'A' | 'B' | 'C') {
  const rent = key === 'B' ? 300000 : key === 'C' ? 340000 : 320000;
  const down = key === 'C' ? 10000000 : 8000000;
  return { analysisKey: 'ATLAS_SYNTHETIC_INVESTMENT_BREAKEVEN_V1', analysisTitle: 'ATLAS Synthetic Investment Breakeven Certification', analysisPurpose: 'Internal Agent financial decision-support certification only.', scenarioKey: `ATLAS_SYNTHETIC_SCENARIO_${key}`, additionalCapitalCents: 18000000, reserveTargetCents: 1500000, review: true, properties: [
    { role: 'EXISTING_PRIMARY', label: 'ATLAS Synthetic Existing Primary', purchasePriceCents: 0, downPaymentCents: 0, closingCostsCents: 0, monthlyTaxesCents: 0, monthlyInsuranceCents: 0, monthlyHoaCents: 0, monthlyRentCents: 0, vacancyBasisPoints: 0, managementBasisPoints: 0, monthlyMaintenanceCents: 0, monthlyCapexReserveCents: 0, annualRateBasisPoints: 0, loanTermMonths: 360, monthlyMortgageInsuranceCents: 0, qualification: 'SYNTHETIC_CERTIFICATION', manualSaleProceedsCents: 15000000 },
    { role: 'NEW_PRIMARY', label: 'ATLAS Synthetic New Primary', purchasePriceCents: 50000000, downPaymentCents: 10000000, closingCostsCents: 900000, monthlyTaxesCents: 55000, monthlyInsuranceCents: 18000, monthlyHoaCents: 0, monthlyRentCents: 0, vacancyBasisPoints: 0, managementBasisPoints: 0, monthlyMaintenanceCents: 0, monthlyCapexReserveCents: 0, annualRateBasisPoints: 650, loanTermMonths: 360, monthlyMortgageInsuranceCents: 0, qualification: 'SYNTHETIC_CERTIFICATION' },
    { role: 'INVESTMENT_PROPERTY', label: 'ATLAS Synthetic Investment Property', purchasePriceCents: 40000000, downPaymentCents: down, closingCostsCents: 700000, monthlyTaxesCents: 40000, monthlyInsuranceCents: 16000, monthlyHoaCents: 15000, monthlyRentCents: rent, vacancyBasisPoints: 500, managementBasisPoints: 800, monthlyMaintenanceCents: 15000, monthlyCapexReserveCents: 12000, annualRateBasisPoints: 675, loanTermMonths: 360, monthlyMortgageInsuranceCents: down < 8000000 ? 15000 : 0, qualification: 'SYNTHETIC_CERTIFICATION' },
  ] };
}

export default function InvestmentBreakevenWorkspace() {
  const [analyses, setAnalyses] = useState<Analysis[]>([]); const [outputs, setOutputs] = useState<Output[]>([]); const [busy, setBusy] = useState(false); const [status, setStatus] = useState('');
  const [comparison, setComparison] = useState<string[]>([]); const [sensitivity, setSensitivity] = useState<Sensitivity | null>(null);
  const [draftKey, setDraftKey] = useState('ATLAS_SYNTHETIC_EDITABLE_DRAFT'); const [draftRent, setDraftRent] = useState('3200'); const [draftDown, setDraftDown] = useState('80000'); const [draftVacancy, setDraftVacancy] = useState('5');
  async function load() { const response = await fetch('/api/agent/investment-breakeven', { cache: 'no-store' }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Unable to restore investment analysis history.'); setAnalyses(body.analyses || []); setOutputs(body.outputs || []); const ids = (body.analyses || []).flatMap((analysis: Analysis) => analysis.scenarios.filter((scenario) => scenario.lifecycleState === 'AGENT_REVIEWED').map((scenario) => scenario.id)); setComparison((current) => current.length ? current.filter((id) => ids.includes(id)) : ids); }
  useEffect(() => { const timer = window.setTimeout(() => { void load().catch((error) => setStatus(error.message)); }, 0); return () => window.clearTimeout(timer); }, []);
  async function action(body: Record<string, unknown>) { const response = await fetch('/api/agent/investment-breakeven', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || 'Unable to complete the investment action.'); return payload; }
  async function create(key: 'A' | 'B' | 'C') { setBusy(true); setStatus(''); try { const body = await action({ action: 'CREATE_SCENARIO', scenario: certificationScenario(key) }); await load(); setStatus(body.created ? `Synthetic scenario ${key} reviewed and persisted.` : `Synthetic scenario ${key} already exists; no duplicate was created.`); } catch (error) { setStatus(error instanceof Error ? error.message : 'Unable to save investment scenario.'); } finally { setBusy(false); } }
  async function createDraft() { setBusy(true); setStatus(''); try { const scenario = certificationScenario('A'); const properties = scenario.properties.map((property) => property.role === 'INVESTMENT_PROPERTY' ? { ...property, monthlyRentCents: Math.round(Number(draftRent) * 100), downPaymentCents: Math.round(Number(draftDown) * 100), vacancyBasisPoints: Math.round(Number(draftVacancy) * 100) } : property); const body = await action({ action: 'CREATE_SCENARIO', scenario: { ...scenario, scenarioKey: draftKey, review: false, properties } }); await load(); setStatus(body.created ? 'Editable draft and immutable calculation persisted. Review is still required.' : 'That editable draft already exists; no duplicate was created.'); } catch (error) { setStatus(error instanceof Error ? error.message : 'Unable to create editable draft.'); } finally { setBusy(false); } }
  async function clone(scenario: Scenario) { setBusy(true); setStatus(''); try { const body = await action({ action: 'CLONE_SCENARIO', clone: { sourceScenarioId: scenario.id, scenarioKey: `${scenario.scenarioKey}_CLONE` } }); await load(); setStatus(body.created ? `${scenario.scenarioKey} was cloned as an editable draft successor.` : 'That scenario clone already exists; no duplicate was created.'); } catch (error) { setStatus(error instanceof Error ? error.message : 'Unable to clone scenario.'); } finally { setBusy(false); } }
  async function review(scenario: Scenario) { setBusy(true); setStatus(''); try { const body = await action({ action: 'REVIEW_SCENARIO', scenarioId: scenario.id }); await load(); setStatus(body.reviewed ? `${scenario.scenarioKey} is Agent reviewed.` : `${scenario.scenarioKey} was already Agent reviewed.`); } catch (error) { setStatus(error instanceof Error ? error.message : 'Unable to review scenario.'); } finally { setBusy(false); } }
  async function runSensitivity(scenario: Scenario) { setBusy(true); setStatus(''); try { const [low, high] = await Promise.all([action({ action: 'CALCULATE_SENSITIVITY', scenarioId: scenario.id, rentDeltaCents: -20000 }), action({ action: 'CALCULATE_SENSITIVITY', scenarioId: scenario.id, rentDeltaCents: 20000 })]); setSensitivity({ scenarioKey: scenario.scenarioKey, low: low.result, high: high.result }); setStatus(`Rent sensitivity calculated from ${scenario.scenarioKey}'s immutable input snapshot; no scenario was changed.`); } catch (error) { setStatus(error instanceof Error ? error.message : 'Unable to calculate sensitivity.'); } finally { setBusy(false); } }
  async function persistOutput(label: string, scenarioIds: string[]) { setBusy(true); setStatus(''); try { const analysis = analyses[0]; if (!analysis) throw new Error('No investment analysis is available.'); const body = await action({ action: 'PERSIST_REVIEWED_OUTPUT', analysisId: analysis.id, scenarioIds }); await load(); setStatus(body.output.created ? `Reviewed Output ${label} persisted through the shared immutable OutputVersion foundation.` : `Reviewed Output ${label} already exists; the identical retry returned the stored version.`); } catch (error) { setStatus(error instanceof Error ? error.message : 'Unable to persist reviewed output.'); } finally { setBusy(false); } }
  const scenarios = useMemo(() => analyses.flatMap((analysis) => analysis.scenarios), [analyses]); const reviewed = scenarios.filter((scenario) => scenario.lifecycleState === 'AGENT_REVIEWED'); const selection = (keys: string[]) => reviewed.filter((scenario) => keys.some((key) => scenario.scenarioKey.endsWith(`_${key}`))).map((scenario) => scenario.id); function toggleComparison(id: string) { setComparison((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); }
  return <main className="min-h-screen bg-[#071014] px-5 py-6 text-slate-100 sm:px-8 sm:py-8 lg:px-12" data-testid="investment-breakeven-workspace" data-agent-only="true" data-client-facing="false"><div className="mx-auto max-w-6xl"><header className="border-b border-white/10 pb-6"><p className="text-[11px] font-bold uppercase tracking-[0.16em] text-cyan-100/70">Project Atlas / Agent Workspace</p><h1 className="mt-2 text-2xl font-semibold sm:text-3xl">Investment Breakeven</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-300">Assumption-based, pre-tax decision support. Results are modeled estimates, not financial advice, lender approval, tax advice, or a return guarantee.</p></header>
    {status && <p className="mt-4 border border-cyan-100/20 bg-cyan-100/[0.06] px-4 py-3 text-sm text-cyan-50" role="status">{status}</p>}
    <section className="mt-6 border border-amber-100/20 bg-amber-100/[0.04] p-5"><div className="flex gap-3"><ShieldAlert className="mt-0.5 text-amber-100" size={18}/><div><h2 className="text-sm font-semibold text-amber-50">Controlled decision-support boundary</h2><p className="mt-1 text-sm leading-6 text-slate-300">This workspace has no lender, provider, client-delivery, document, CRM, MLS, or Client Portal action. Inputs retain their qualification and outputs remain Agent-internal.</p></div></div></section>
    <section className="mt-6 border border-white/10 bg-white/[0.035] p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-semibold">Synthetic certification scenarios</p><p className="mt-1 text-sm text-slate-400">A is baseline, B is rent stress, and C is higher-rent/higher-down-payment comparison.</p></div><div className="flex flex-wrap gap-2">{(['A','B','C'] as const).map((key) => <button key={key} type="button" disabled={busy} onClick={() => void create(key)} className="inline-flex min-h-10 items-center gap-2 border border-cyan-100/35 px-3 text-sm font-semibold text-cyan-50 disabled:opacity-50"><CopyPlus size={15}/>Create {key}</button>)}</div></div></section>
    <section className="mt-6 border border-white/10 bg-white/[0.035] p-5" aria-label="Editable Agent assumptions"><div className="flex items-center gap-2"><FlaskConical size={17} className="text-cyan-100"/><h2 className="text-sm font-semibold">Editable Agent assumptions</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Field label="Scenario key" value={draftKey} onChange={setDraftKey}/><Field label="Monthly rent" value={draftRent} onChange={setDraftRent} inputMode="decimal"/><Field label="Down payment" value={draftDown} onChange={setDraftDown} inputMode="decimal"/><Field label="Vacancy %" value={draftVacancy} onChange={setDraftVacancy} inputMode="decimal"/></div><button type="button" disabled={busy} onClick={() => void createDraft()} className="mt-4 inline-flex min-h-10 items-center gap-2 border border-cyan-100/35 px-3 text-sm font-semibold text-cyan-50 disabled:opacity-50"><CopyPlus size={15}/>Save editable draft</button></section>
    <section className="mt-6 border border-white/10 bg-white/[0.035] p-5" aria-label="Reviewed output composition"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-sm font-semibold">Comparison and reviewed output</h2><p className="mt-1 text-sm text-slate-400">Select reviewed scenario results, then persist a bounded Agent-internal comparison through the shared output foundation.</p></div><div className="flex flex-wrap gap-2"><button type="button" disabled={busy} onClick={() => void persistOutput('A', selection(['A','B','C']))} className="inline-flex min-h-10 items-center gap-2 border border-emerald-200/35 px-3 text-sm font-semibold text-emerald-50 disabled:opacity-50"><FileCheck2 size={15}/>Persist Output A</button><button type="button" disabled={busy} onClick={() => void persistOutput('B', selection(['A','C']))} className="inline-flex min-h-10 items-center gap-2 border border-emerald-200/35 px-3 text-sm font-semibold text-emerald-50 disabled:opacity-50"><FileCheck2 size={15}/>Persist Output B</button><button type="button" disabled={busy || comparison.length < 2} onClick={() => void persistOutput('selection', comparison)} className="inline-flex min-h-10 items-center gap-2 border border-white/25 px-3 text-sm font-semibold text-slate-100 disabled:opacity-50"><FileCheck2 size={15}/>Persist selection</button></div></div><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-sm">{reviewed.map((scenario) => <label key={scenario.id} className="inline-flex items-center gap-2 text-slate-300"><input type="checkbox" checked={comparison.includes(scenario.id)} onChange={() => toggleComparison(scenario.id)} className="h-4 w-4 accent-cyan-200"/>{scenario.scenarioKey}</label>)}</div>{outputs.length > 0 && <div className="mt-4 border-t border-white/10 pt-3 text-xs text-slate-400">{outputs.slice(0, 4).map((output) => <p key={output.id} className="mt-1"><CheckCircle2 size={13} className="mr-1 inline text-emerald-200"/>{output.displayVersion} · immutable output {output.versionOrdinal}</p>)}</div>}</section>
    {sensitivity && <section className="mt-6 border border-white/10 bg-white/[0.035] p-5"><h2 className="text-sm font-semibold">Rent sensitivity: {sensitivity.scenarioKey}</h2><div className="mt-3 grid gap-3 sm:grid-cols-2"><SensitivityMetric label="Minus $200 rent" result={sensitivity.low}/><SensitivityMetric label="Plus $200 rent" result={sensitivity.high}/></div></section>}
    <section className="mt-6 space-y-4" aria-label="Investment analysis history">{!analyses.length && <p className="border border-white/10 bg-white/[0.035] p-6 text-sm text-slate-400">No investment analyses are available to this Agent.</p>}{analyses.map((analysis) => <article key={analysis.id} className="border border-white/10 bg-white/[0.035] p-5"><h2 className="text-lg font-semibold">{analysis.title}</h2><p className="mt-1 text-sm text-slate-400">{analysis.purpose}</p><div className="mt-5 grid gap-4 lg:grid-cols-3">{analysis.scenarios.map((scenario) => <ScenarioCard key={scenario.id} scenario={scenario} busy={busy} onClone={clone} onReview={review} onSensitivity={runSensitivity}/>)}</div></article>)}</section>
  </div></main>;
}
function Field({ label, value, onChange, inputMode }: { label: string; value: string; onChange: (value: string) => void; inputMode?: 'decimal' }) { return <label className="text-xs text-slate-400">{label}<input value={value} inputMode={inputMode} onChange={(event) => onChange(event.target.value)} className="mt-1 block min-h-10 w-full border border-white/15 bg-black/20 px-3 text-sm text-slate-100"/></label>; }
function ScenarioCard({ scenario, busy, onClone, onReview, onSensitivity }: { scenario: Scenario; busy: boolean; onClone: (scenario: Scenario) => void; onReview: (scenario: Scenario) => void; onSensitivity: (scenario: Scenario) => void }) { const result = scenario.result?.resultSnapshot || {}; return <section className="border border-white/10 bg-black/10 p-4"><div className="flex items-start justify-between gap-2"><div><p className="text-xs font-semibold uppercase tracking-[0.1em] text-cyan-100/70">{scenario.scenarioKey}</p><h3 className="mt-1 font-semibold">{scenario.lifecycleState.replaceAll('_', ' ')}</h3></div><TrendingUp size={18} className="text-cyan-100"/></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><Metric label="Available capital" value={money(result.availableCapitalCents)}/><Metric label="Cash required" value={money(result.totalCashRequiredCents)}/><Metric label="Remaining liquidity" value={money(result.remainingLiquidityCents)}/><Metric label="Investment cash flow" value={money(result.investmentMonthlyCashFlowCents)}/><Metric label="NOI" value={money(result.investmentAnnualNoiCents)}/><Metric label="Cap rate" value={percent(result.investmentCapRateBasisPoints)}/><Metric label="Pre-tax cash-on-cash" value={percent(result.investmentPreTaxCashOnCashBasisPoints)}/><Metric label="Breakeven rent" value={money(result.investmentBreakevenRentCents)}/></dl><div className="mt-4 flex flex-wrap gap-2 border-t border-white/10 pt-3"><button type="button" disabled={busy} onClick={() => onClone(scenario)} className="inline-flex min-h-9 items-center gap-1 border border-white/20 px-2 text-xs text-slate-200 disabled:opacity-50"><CopyPlus size={13}/>Clone</button>{scenario.lifecycleState === 'DRAFT' && <button type="button" disabled={busy} onClick={() => onReview(scenario)} className="inline-flex min-h-9 items-center gap-1 border border-emerald-200/35 px-2 text-xs text-emerald-50 disabled:opacity-50"><CheckCircle2 size={13}/>Review</button>}<button type="button" disabled={busy} onClick={() => onSensitivity(scenario)} className="inline-flex min-h-9 items-center gap-1 border border-cyan-100/30 px-2 text-xs text-cyan-50 disabled:opacity-50"><FlaskConical size={13}/>Sensitivity</button></div><div className="mt-4 border-t border-white/10 pt-3 text-xs text-slate-400"><p className="font-semibold text-slate-300">Qualification</p>{scenario.inputSnapshot.properties?.map((property) => <p key={property.role} className="mt-1">{property.label}: {property.qualification.replaceAll('_', ' ')}</p>)}<p className="mt-3">Modeled estimates are pre-tax and require Agent interpretation.</p></div></section> }
function SensitivityMetric({ label, result }: { label: string; result?: Record<string, unknown> }) { return <div className="border border-white/10 bg-black/10 p-3"><p className="text-xs text-slate-400">{label}</p><p className="mt-1 text-sm font-semibold">Investment cash flow {money(result?.investmentMonthlyCashFlowCents)}</p><p className="mt-1 text-sm text-slate-300">Breakeven rent {money(result?.investmentBreakevenRentCents)}</p></div> }
function Metric({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 font-semibold text-slate-200">{value}</dd></div> }
