'use client';

import { useEffect, useState } from 'react';
import { CopyPlus, ShieldAlert, TrendingUp } from 'lucide-react';

type Scenario = { id: string; scenarioKey: string; versionOrdinal: number; lifecycleState: string; inputSnapshot: { properties?: Array<{ role: string; label: string; qualification: string }> }; result?: { resultSnapshot: Record<string, unknown>; resultFingerprint: string } | null };
type Analysis = { id: string; title: string; purpose: string; scenarios: Scenario[] };
const money = (value: unknown) => typeof value === 'number' ? new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(value / 100) : 'Not applicable';
const percent = (value: unknown) => typeof value === 'number' ? `${(value / 100).toFixed(2)}%` : 'Not applicable';

function certificationScenario(key: 'A' | 'B' | 'C') {
  const rent = key === 'B' ? 300000 : key === 'C' ? 340000 : 320000;
  const down = key === 'C' ? 10000000 : 8000000;
  return { analysisKey: 'ATLAS_SYNTHETIC_INVESTMENT_BREAKEVEN_V1', analysisTitle: 'ATLAS Synthetic Investment Breakeven Certification', analysisPurpose: 'Internal Agent financial decision-support certification only.', scenarioKey: `ATLAS_SYNTHETIC_SCENARIO_${key}`, additionalCapitalCents: 18000000, reserveTargetCents: 1500000, review: true, properties: [
    { role: 'EXISTING_PRIMARY', label: 'ATLAS Synthetic Existing Primary', purchasePriceCents: 0, downPaymentCents: 0, closingCostsCents: 0, monthlyTaxesCents: 0, monthlyInsuranceCents: 0, monthlyHoaCents: 0, monthlyRentCents: 0, vacancyBasisPoints: 0, managementBasisPoints: 0, monthlyMaintenanceCents: 0, monthlyCapexReserveCents: 0, annualRateBasisPoints: 0, loanTermMonths: 360, monthlyMortgageInsuranceCents: 0, qualification: 'SYNTHETIC_CERTIFICATION', manualSaleProceedsCents: 15000000 },
    { role: 'NEW_PRIMARY', label: 'ATLAS Synthetic New Primary', purchasePriceCents: 50000000, downPaymentCents: 10000000, closingCostsCents: 900000, monthlyTaxesCents: 55000, monthlyInsuranceCents: 18000, monthlyHoaCents: 0, monthlyRentCents: 0, vacancyBasisPoints: 0, managementBasisPoints: 0, monthlyMaintenanceCents: 0, monthlyCapexReserveCents: 0, annualRateBasisPoints: 650, loanTermMonths: 360, monthlyMortgageInsuranceCents: 0, qualification: 'SYNTHETIC_CERTIFICATION' },
    { role: 'INVESTMENT_PROPERTY', label: 'ATLAS Synthetic Investment Property', purchasePriceCents: 40000000, downPaymentCents: down, closingCostsCents: 700000, monthlyTaxesCents: 40000, monthlyInsuranceCents: 16000, monthlyHoaCents: 15000, monthlyRentCents: rent, vacancyBasisPoints: 500, managementBasisPoints: 800, monthlyMaintenanceCents: 15000, monthlyCapexReserveCents: 12000, annualRateBasisPoints: 675, loanTermMonths: 360, monthlyMortgageInsuranceCents: down < 8000000 ? 15000 : 0, qualification: 'SYNTHETIC_CERTIFICATION' },
  ] };
}

export default function InvestmentBreakevenWorkspace() {
  const [analyses, setAnalyses] = useState<Analysis[]>([]); const [busy, setBusy] = useState(false); const [status, setStatus] = useState('');
  async function load() { const response = await fetch('/api/agent/investment-breakeven', { cache: 'no-store' }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Unable to restore investment analysis history.'); setAnalyses(body.analyses || []); }
  useEffect(() => { const timer = window.setTimeout(() => { void load().catch((error) => setStatus(error.message)); }, 0); return () => window.clearTimeout(timer); }, []);
  async function create(key: 'A' | 'B' | 'C') { setBusy(true); setStatus(''); try { const response = await fetch('/api/agent/investment-breakeven', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'CREATE_SCENARIO', scenario: certificationScenario(key) }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Unable to save investment scenario.'); await load(); setStatus(body.created ? `Synthetic scenario ${key} reviewed and persisted.` : `Synthetic scenario ${key} already exists; no duplicate was created.`); } catch (error) { setStatus(error instanceof Error ? error.message : 'Unable to save investment scenario.'); } finally { setBusy(false); } }
  return <main className="min-h-screen bg-[#071014] px-5 py-6 text-slate-100 sm:px-8 sm:py-8 lg:px-12" data-testid="investment-breakeven-workspace" data-agent-only="true" data-client-facing="false">
    <div className="mx-auto max-w-6xl"><header className="border-b border-white/10 pb-6"><p className="text-[11px] font-bold uppercase tracking-[0.16em] text-cyan-100/70">Project Atlas / Agent Workspace</p><h1 className="mt-2 text-2xl font-semibold sm:text-3xl">Investment Breakeven</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-300">Assumption-based, pre-tax decision support. Results are modeled estimates, not financial advice, lender approval, tax advice, or a return guarantee.</p></header>
      {status && <p className="mt-4 border border-cyan-100/20 bg-cyan-100/[0.06] px-4 py-3 text-sm text-cyan-50" role="status">{status}</p>}
      <section className="mt-6 border border-amber-100/20 bg-amber-100/[0.04] p-5"><div className="flex gap-3"><ShieldAlert className="mt-0.5 text-amber-100" size={18}/><div><h2 className="text-sm font-semibold text-amber-50">Controlled decision-support boundary</h2><p className="mt-1 text-sm leading-6 text-slate-300">This workspace has no lender, provider, client-delivery, document, CRM, MLS, or Client Portal action. Inputs retain their qualification and outputs remain Agent-internal.</p></div></div></section>
      <section className="mt-6 border border-white/10 bg-white/[0.035] p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-semibold">Synthetic certification scenarios</p><p className="mt-1 text-sm text-slate-400">A is baseline, B is rent stress, and C is higher-rent/higher-down-payment comparison.</p></div><div className="flex flex-wrap gap-2">{(['A','B','C'] as const).map((key) => <button key={key} type="button" disabled={busy} onClick={() => void create(key)} className="inline-flex min-h-10 items-center gap-2 border border-cyan-100/35 px-3 text-sm font-semibold text-cyan-50 disabled:opacity-50"><CopyPlus size={15}/>Create {key}</button>)}</div></div></section>
      <section className="mt-6 space-y-4" aria-label="Investment analysis history">{!analyses.length && <p className="border border-white/10 bg-white/[0.035] p-6 text-sm text-slate-400">No investment analyses are available to this Agent.</p>}{analyses.map((analysis) => <article key={analysis.id} className="border border-white/10 bg-white/[0.035] p-5"><h2 className="text-lg font-semibold">{analysis.title}</h2><p className="mt-1 text-sm text-slate-400">{analysis.purpose}</p><div className="mt-5 grid gap-4 lg:grid-cols-3">{analysis.scenarios.map((scenario) => <ScenarioCard key={scenario.id} scenario={scenario}/>)}</div></article>)}</section>
    </div></main>;
}
function ScenarioCard({ scenario }: { scenario: Scenario }) { const result = scenario.result?.resultSnapshot || {}; return <section className="border border-white/10 bg-black/10 p-4"><div className="flex items-start justify-between gap-2"><div><p className="text-xs font-semibold uppercase tracking-[0.1em] text-cyan-100/70">{scenario.scenarioKey}</p><h3 className="mt-1 font-semibold">{scenario.lifecycleState.replaceAll('_', ' ')}</h3></div><TrendingUp size={18} className="text-cyan-100"/></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><Metric label="Available capital" value={money(result.availableCapitalCents)}/><Metric label="Cash required" value={money(result.totalCashRequiredCents)}/><Metric label="Remaining liquidity" value={money(result.remainingLiquidityCents)}/><Metric label="Investment cash flow" value={money(result.investmentMonthlyCashFlowCents)}/><Metric label="NOI" value={money(result.investmentAnnualNoiCents)}/><Metric label="Cap rate" value={percent(result.investmentCapRateBasisPoints)}/><Metric label="Pre-tax cash-on-cash" value={percent(result.investmentPreTaxCashOnCashBasisPoints)}/><Metric label="Breakeven rent" value={money(result.investmentBreakevenRentCents)}/></dl><div className="mt-4 border-t border-white/10 pt-3 text-xs text-slate-400"><p className="font-semibold text-slate-300">Qualification</p>{scenario.inputSnapshot.properties?.map((property) => <p key={property.role} className="mt-1">{property.label}: {property.qualification.replaceAll('_', ' ')}</p>)}<p className="mt-3">Modeled estimates are pre-tax and require Agent interpretation.</p></div></section> }
function Metric({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 font-semibold text-slate-200">{value}</dd></div> }
