'use client';

import { useEffect, useMemo, useState } from 'react';
import { BarChart3, CopyPlus, FileOutput, GitCompareArrows, Landmark, Plus, Sparkles } from 'lucide-react';
import { useSearchParams } from 'next/navigation';

type PropertyDraft = { role: string; referenceType: string; label: string; value: string; debt: string; downPayment: string; closingCosts: string; rent: string; taxes: string; insurance: string; hoa: string; maintenance: string; capex: string; rate: string; term: string };
type Version = { id: string; versionOrdinal: number; inputFingerprint: string; inputSnapshot: Record<string, unknown>; result: { id: string; resultFingerprint: string; resultSnapshot: ResultSnapshot } | null; outputVersions: { id: string; lifecycleState: string; reviewState: string }[] };
type Scenario = { id: string; scenarioKey: string; displayName: string; clientCaseId: string | null; lifecycleState: string; versions: Version[] };
type ResultSnapshot = { liquidity?: Record<string, number>; cashFlow?: Record<string, number>; timing?: Record<string, number | boolean>; properties?: { label: string; role: string; monthlyCashFlowCents: number; saleProceedsCents: number; acquisitionCashRequiredCents: number; breakevenRentCents: number | null }[] };

const money = (value: unknown) => typeof value === 'number' ? new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(value / 100) : 'Not available';
const draftProperty = (role: string, label: string): PropertyDraft => ({ role, referenceType: 'HYPOTHETICAL', label, value: role === 'CURRENT_HOME_SELL' ? '800000' : '650000', debt: role === 'CURRENT_HOME_SELL' ? '400000' : '0', downPayment: role === 'CURRENT_HOME_SELL' ? '0' : '130000', closingCosts: role === 'CURRENT_HOME_SELL' ? '0' : '13000', rent: '0', taxes: '600', insurance: '180', hoa: '0', maintenance: '120', capex: '80', rate: '650', term: '360' });

function asCents(value: string) { const parsed = Number(value); return Number.isFinite(parsed) && parsed >= 0 ? Math.round(parsed * 100) : 0; }
function asInteger(value: string) { const parsed = Number(value); return Number.isInteger(parsed) && parsed >= 0 ? parsed : 0; }
function versionInput(key: string, name: string, clientCaseId: string | null, properties: PropertyDraft[]) {
  return {
    clientCaseId, scenarioKey: key, displayName: name, additionalLiquidCapitalCents: 0, reserveTargetCents: 50000 * 100, saleClosingCostBasisPoints: 600, timing: { saleMonth: 1, acquisitionMonth: 0 },
    properties: properties.map((property) => ({ role: property.role, referenceType: property.referenceType, canonicalPropertyId: null, label: property.label, valueCents: asCents(property.value), debtBalanceCents: asCents(property.debt), downPaymentCents: asCents(property.downPayment), closingCostsCents: asCents(property.closingCosts), monthlyRentCents: asCents(property.rent), monthlyTaxesCents: asCents(property.taxes), monthlyInsuranceCents: asCents(property.insurance), monthlyHoaCents: asCents(property.hoa), monthlyMaintenanceCents: asCents(property.maintenance), monthlyCapexReserveCents: asCents(property.capex), monthlyMortgageInsuranceCents: 0, vacancyBasisPoints: 500, managementBasisPoints: 800, annualRateBasisPoints: asInteger(property.rate), loanTermMonths: Math.max(1, asInteger(property.term)), qualification: property.label.startsWith('ATLAS Synthetic') ? 'SYNTHETIC_CERTIFICATION' : 'AGENT_ESTIMATE' })),
  };
}

export default function MultiPropertyFinancialScenarioWorkspace() {
  const params = useSearchParams(); const clientCaseId = params.get('clientCaseId');
  const [scenarios, setScenarios] = useState<Scenario[]>([]); const [status, setStatus] = useState(''); const [busy, setBusy] = useState(false); const [comparison, setComparison] = useState<string[]>([]); const [comparisonResult, setComparisonResult] = useState<{ displayName: string; versionOrdinal: number; resultSnapshot: ResultSnapshot }[]>([]);
  const [scenarioKey, setScenarioKey] = useState('ATLAS_SYNTHETIC_MULTI_PROPERTY_SCENARIO'); const [displayName, setDisplayName] = useState('ATLAS Synthetic Multi-Property Financial Scenario');
  const [properties, setProperties] = useState<PropertyDraft[]>([draftProperty('CURRENT_HOME_SELL', 'ATLAS Synthetic Current Home'), draftProperty('REPLACEMENT_PRIMARY_ACQUIRE', 'ATLAS Synthetic Replacement Primary')]);
  async function load() { const response = await fetch(`/api/agent/multi-property-financial-scenarios${clientCaseId ? `?clientCaseId=${encodeURIComponent(clientCaseId)}` : ''}`, { cache: 'no-store' }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Unable to load scenario history.'); setScenarios(body.scenarios || []); }
  useEffect(() => {
    const timer = window.setTimeout(() => {
      void fetch(`/api/agent/multi-property-financial-scenarios${clientCaseId ? `?clientCaseId=${encodeURIComponent(clientCaseId)}` : ''}`, { cache: 'no-store' })
        .then(async (response) => {
          const body = await response.json();
          if (!response.ok) throw new Error(body.error || 'Unable to load scenario history.');
          setScenarios(body.scenarios || []);
        })
        .catch((error: unknown) => setStatus(error instanceof Error ? error.message : 'Unable to load scenario history.'));
    }, 0);
    return () => window.clearTimeout(timer);
  }, [clientCaseId]);
  async function action(body: Record<string, unknown>) { const response = await fetch('/api/agent/multi-property-financial-scenarios', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Unable to complete scenario action.'); return result; }
  async function create() { setBusy(true); try { const result = await action({ action: 'CREATE_SCENARIO', input: versionInput(scenarioKey, displayName, clientCaseId, properties) }); await load(); setStatus(result.created ? 'Immutable ScenarioVersion created. Run analysis explicitly to materialize its result.' : 'That exact immutable ScenarioVersion already exists; no duplicate was created.'); } catch (error) { setStatus(error instanceof Error ? error.message : 'Unable to create the scenario.'); } finally { setBusy(false); } }
  async function analyze(versionId: string) { setBusy(true); try { const result = await action({ action: 'ANALYZE_VERSION', versionId }); await load(); setStatus(result.created ? 'Immutable result materialized from the exact ScenarioVersion.' : 'This version already has its immutable result.'); } catch (error) { setStatus(error instanceof Error ? error.message : 'Unable to analyze the version.'); } finally { setBusy(false); } }
  async function output(versionId: string) { setBusy(true); try { const result = await action({ action: 'CREATE_OUTPUT_DRAFT', versionId }); await load(); setStatus(result.output.created ? 'Review-required semantic OutputVersion prepared. No render or delivery occurred.' : 'The exact semantic OutputVersion already exists.'); } catch (error) { setStatus(error instanceof Error ? error.message : 'Unable to prepare the OutputVersion.'); } finally { setBusy(false); } }
  async function revise(version: Version) { setBusy(true); try { const result = await action({ action: 'CREATE_REVISION', predecessorVersionId: version.id, input: version.inputSnapshot }); await load(); setStatus(result.created ? 'Immutable successor ScenarioVersion created with the same frozen scope.' : 'A successor for this version already exists.'); } catch (error) { setStatus(error instanceof Error ? error.message : 'Unable to create the scenario revision.'); } finally { setBusy(false); } }
  async function compare() { setBusy(true); try { const result = await action({ action: 'COMPARE_VERSIONS', versionIds: comparison }); setComparisonResult(result.comparison || []); setStatus('Exact immutable scenario results compared without changing persisted records.'); } catch (error) { setStatus(error instanceof Error ? error.message : 'Unable to compare selected versions.'); } finally { setBusy(false); } }
  const versions = useMemo(() => scenarios.flatMap((scenario) => scenario.versions.map((version) => ({ scenario, version }))), [scenarios]);
  function updateProperty(index: number, key: keyof PropertyDraft, value: string) { setProperties((current) => current.map((property, itemIndex) => itemIndex === index ? { ...property, [key]: value } : property)); }
  return <section className="border-b border-white/10 bg-[#08151a] px-5 py-8 sm:px-8 lg:px-12" data-testid="multi-property-financial-scenario-workspace">
    <div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-cyan-100/70">Financial Strategy / Scenario Foundation</p><h1 className="mt-2 text-2xl font-semibold text-white">Multi-property financial scenarios</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-300">Coordinated sell, retain, replacement, and investment scenarios. Each version and result is immutable; no recommendation, client delivery, render, or external action is performed here.</p></div><Landmark size={24} className="text-cyan-100" aria-hidden="true" /></div>
    {status ? <p className="mt-5 border border-cyan-100/20 bg-cyan-100/[0.06] px-4 py-3 text-sm text-cyan-50" role="status">{status}</p> : null}
    <section className="mt-6 border border-white/10 bg-white/[0.035] p-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-sm font-semibold text-white">New immutable scenario version</h2><p className="mt-1 text-sm text-slate-400">The form begins with synthetic labels for controlled certification. Add any number of participants; current and replacement primary roles remain singular.</p></div><button type="button" onClick={() => setProperties((items) => [...items, draftProperty('INVESTMENT_ACQUIRE', `ATLAS Synthetic Investment ${items.length - 1}`)])} className="inline-flex min-h-10 items-center gap-2 border border-white/20 px-3 text-sm text-slate-200"><Plus size={15}/>Add participant</button></div>
      <div className="mt-4 grid gap-3 md:grid-cols-2"><label className="text-xs text-slate-400">Scenario key<input value={scenarioKey} onChange={(event) => setScenarioKey(event.target.value)} className="mt-1 min-h-10 w-full border border-white/20 bg-black/20 px-3 text-sm text-white" /></label><label className="text-xs text-slate-400">Display name<input value={displayName} onChange={(event) => setDisplayName(event.target.value)} className="mt-1 min-h-10 w-full border border-white/20 bg-black/20 px-3 text-sm text-white" /></label></div>
      <div className="mt-5 grid gap-4 lg:grid-cols-2">{properties.map((property, index) => <article key={`${property.role}-${index}`} className="border border-white/10 p-4"><div className="flex items-center justify-between gap-3"><p className="text-sm font-semibold text-white">Participant {index + 1}</p>{properties.length > 1 ? <button type="button" onClick={() => setProperties((items) => items.filter((_, itemIndex) => itemIndex !== index))} className="text-xs text-slate-400 hover:text-white">Remove</button> : null}</div><div className="mt-3 grid grid-cols-2 gap-3"><Field label="Label" value={property.label} onChange={(value) => updateProperty(index, 'label', value)} /><Select label="Role" value={property.role} onChange={(value) => updateProperty(index, 'role', value)} options={['CURRENT_HOME_SELL', 'CURRENT_HOME_RETAIN', 'REPLACEMENT_PRIMARY_ACQUIRE', 'INVESTMENT_ACQUIRE']} /><Select label="Reference" value={property.referenceType} onChange={(value) => updateProperty(index, 'referenceType', value)} options={['HYPOTHETICAL', 'PROSPECTIVE']} /><Field label="Value / price" value={property.value} onChange={(value) => updateProperty(index, 'value', value)} /><Field label="Debt balance" value={property.debt} onChange={(value) => updateProperty(index, 'debt', value)} /><Field label="Down payment" value={property.downPayment} onChange={(value) => updateProperty(index, 'downPayment', value)} /><Field label="Closing costs" value={property.closingCosts} onChange={(value) => updateProperty(index, 'closingCosts', value)} /><Field label="Monthly rent" value={property.rent} onChange={(value) => updateProperty(index, 'rent', value)} /><Field label="Monthly taxes" value={property.taxes} onChange={(value) => updateProperty(index, 'taxes', value)} /><Field label="Insurance" value={property.insurance} onChange={(value) => updateProperty(index, 'insurance', value)} /><Field label="HOA" value={property.hoa} onChange={(value) => updateProperty(index, 'hoa', value)} /><Field label="Maintenance" value={property.maintenance} onChange={(value) => updateProperty(index, 'maintenance', value)} /><Field label="Capex reserve" value={property.capex} onChange={(value) => updateProperty(index, 'capex', value)} /><Field label="Rate bps" value={property.rate} onChange={(value) => updateProperty(index, 'rate', value)} /><Field label="Term months" value={property.term} onChange={(value) => updateProperty(index, 'term', value)} /></div></article>)}</div>
      <button type="button" disabled={busy} onClick={() => void create()} className="mt-5 inline-flex min-h-10 items-center gap-2 border border-cyan-100/35 px-4 text-sm font-semibold text-cyan-50 disabled:opacity-50"><Sparkles size={15}/>Create immutable version</button></section>
    <section className="mt-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-sm font-semibold text-white">Owned scenario versions</h2><p className="mt-1 text-sm text-slate-400">Scoped to {clientCaseId ? 'the selected Client Case' : 'your Agent workspace'}.</p></div><button type="button" disabled={busy || comparison.length < 2} onClick={() => void compare()} className="inline-flex min-h-10 items-center gap-2 border border-emerald-200/35 px-3 text-sm text-emerald-50 disabled:opacity-50"><GitCompareArrows size={15}/>Compare exact versions</button></div>
      <div className="mt-4 grid gap-4 lg:grid-cols-2">{versions.map(({ scenario, version }) => <ScenarioVersionCard key={version.id} scenario={scenario} version={version} busy={busy} selected={comparison.includes(version.id)} onSelect={() => setComparison((current) => current.includes(version.id) ? current.filter((id) => id !== version.id) : [...current, version.id])} onAnalyze={analyze} onOutput={output} onRevise={revise} />)}</div></section>
    {comparisonResult.length ? <section className="mt-6 border border-white/10 bg-white/[0.035] p-5"><h2 className="text-sm font-semibold text-white">Exact-version comparison</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{comparisonResult.map((item) => <div key={`${item.displayName}-${item.versionOrdinal}`} className="border border-white/10 p-3"><p className="font-medium text-white">{item.displayName} / v{item.versionOrdinal}</p><p className="mt-2 text-sm text-slate-300">Liquidity after timed actions: {money(item.resultSnapshot.liquidity?.liquidCapitalAfterTimedActionsCents)}</p><p className="text-sm text-slate-300">Monthly cash flow: {money(item.resultSnapshot.cashFlow?.monthlyCashFlowCents)}</p></div>)}</div></section> : null}
  </div></section>;
}

function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="text-xs text-slate-400">{label}<input value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 min-h-9 w-full border border-white/20 bg-black/20 px-2 text-sm text-white" /></label>; }
function Select({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <label className="text-xs text-slate-400">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 min-h-9 w-full border border-white/20 bg-black/20 px-2 text-sm text-white">{options.map((option) => <option key={option} value={option}>{option.replaceAll('_', ' ')}</option>)}</select></label>; }
function ScenarioVersionCard({ scenario, version, busy, selected, onSelect, onAnalyze, onOutput, onRevise }: { scenario: Scenario; version: Version; busy: boolean; selected: boolean; onSelect: () => void; onAnalyze: (id: string) => void; onOutput: (id: string) => void; onRevise: (version: Version) => void }) { const result = version.result?.resultSnapshot; return <article className="border border-white/10 bg-white/[0.035] p-5"><div className="flex justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.1em] text-cyan-100/70">{scenario.scenarioKey}</p><h3 className="mt-1 font-semibold text-white">{scenario.displayName}</h3><p className="mt-1 text-xs text-slate-400">Immutable version {version.versionOrdinal} · {version.inputFingerprint.slice(0, 12)}</p></div><label className="inline-flex items-center gap-2 text-xs text-slate-300"><input type="checkbox" checked={selected} onChange={onSelect} />Compare</label></div>{result ? <div className="mt-4 grid grid-cols-2 gap-3 text-sm"><Metric label="Timed liquidity" value={money(result.liquidity?.liquidCapitalAfterTimedActionsCents)} /><Metric label="Bridge liquidity" value={money(result.liquidity?.requiresBridgeLiquidityCents)} /><Metric label="Monthly cash flow" value={money(result.cashFlow?.monthlyCashFlowCents)} /><Metric label="Sale proceeds" value={money(result.liquidity?.saleProceedsCents)} /></div> : <p className="mt-4 text-sm text-amber-100/80">Analysis has not been materialized for this immutable version.</p>}<div className="mt-4 flex flex-wrap gap-2 border-t border-white/10 pt-3">{!result ? <button type="button" disabled={busy} onClick={() => onAnalyze(version.id)} className="inline-flex min-h-9 items-center gap-1 border border-cyan-100/30 px-2 text-xs text-cyan-50 disabled:opacity-50"><BarChart3 size={13}/>Analyze</button> : <button type="button" disabled={busy} onClick={() => onOutput(version.id)} className="inline-flex min-h-9 items-center gap-1 border border-emerald-200/35 px-2 text-xs text-emerald-50 disabled:opacity-50"><FileOutput size={13}/>Prepare Output</button>}<button type="button" disabled={busy} onClick={() => onRevise(version)} className="inline-flex min-h-9 items-center gap-1 border border-white/20 px-2 text-xs text-slate-200 disabled:opacity-50"><CopyPlus size={13}/>Create revision</button>{version.outputVersions.map((output) => <span key={output.id} className="inline-flex min-h-9 items-center border border-white/15 px-2 text-xs text-slate-400">Output {output.lifecycleState.replaceAll('_', ' ')}</span>)}</div></article> }
function Metric({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 font-semibold text-slate-100">{value}</dd></div>; }
