'use client';

import Link from 'next/link';
import { ArrowLeft, CalendarClock, ChevronRight, History, ShieldCheck } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { useSearchParams } from 'next/navigation';

import { humanizeTransactionValue } from '@/lib/transactionPresentation';

type Detail = { id: string; displayTitle: string; side: string; status: string; stage: string; propertyDisplay: string; clientCase: { id: string; displayName: string } | null; canonicalPropertyId: string | null; parties: { id: string; role: string; displayLabelSnapshot: string; clientCaseParty: { role: string } }[]; timelineEvents: { id: string; eventType: string; occurredAt: string | null; recordedAt: string; payload: Record<string, unknown> }[]; closedAt: string | null; cancelledAt: string | null };

async function request(path: string, body?: Record<string, unknown>) { const response = await fetch(path, body ? { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) } : { cache: 'no-store' }); const payload = await response.json() as Record<string, unknown>; if (!response.ok) throw new Error(typeof payload.error === 'string' ? payload.error : 'Transaction request failed.'); return payload; }
function dateTime(value: string | null) { return value ? new Date(value).toLocaleString() : 'Not recorded'; }
function eventLabel(eventType: string) { return humanizeTransactionValue(eventType.replace('TRANSACTION_', '').replace('STAGE_REPORTED', 'STAGE_UPDATED')); }

export default function TransactionDetailWorkspace({ transactionId }: { transactionId: string }) {
  const searchParams = useSearchParams(); const contextualCaseId = searchParams.get('clientCaseId');
  const [detail, setDetail] = useState<Detail | null>(null); const [status, setStatus] = useState(''); const [busy, setBusy] = useState(false);
  const [nextStatus, setNextStatus] = useState(''); const [nextStage, setNextStage] = useState(''); const [propertyId, setPropertyId] = useState('');
  const load = useCallback(async () => { const payload = await request(`/api/agent/transactions?id=${encodeURIComponent(transactionId)}`); setDetail(payload.transaction as Detail); }, [transactionId]);
  useEffect(() => { const timer = window.setTimeout(() => { void load().catch((error) => setStatus(error instanceof Error ? error.message : 'Transaction request failed.')); }, 0); return () => window.clearTimeout(timer); }, [load]);
  async function mutate(action: string, input: Record<string, unknown>) { setBusy(true); setStatus(''); try { await request('/api/agent/transactions', { action, transactionId, input }); await load(); setStatus('Transaction updated.'); } catch (error) { setStatus(error instanceof Error ? error.message : 'Transaction request failed.'); } finally { setBusy(false); } }
  const returnCaseId = detail?.clientCase?.id || contextualCaseId;
  return <main className="px-5 py-8 sm:px-8 lg:px-12" data-testid="transaction-detail-workspace"><div className="mx-auto max-w-5xl">
    <Link href={returnCaseId ? `/agent/transactions?clientCaseId=${encodeURIComponent(returnCaseId)}` : '/agent/transactions'} className="inline-flex min-h-10 items-center gap-2 text-sm font-semibold text-cyan-100 hover:text-white"><ArrowLeft size={16} />{returnCaseId ? 'Case Transactions' : 'Transactions'}</Link>
    {status && <p className="atlas-workspace-status mt-5" role="status">{status}</p>}
    {!detail ? <p className="mt-8 text-slate-300">Loading Transaction...</p> : <><header className="mt-6 border-b border-white/10 pb-6"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-cyan-100/70">Project Atlas / Transaction</p><h1 className="mt-2 text-2xl font-semibold text-white sm:text-3xl">{detail.displayTitle}</h1><p className="mt-3 text-sm text-slate-300">{humanizeTransactionValue(detail.side)} · {humanizeTransactionValue(detail.status)} · {humanizeTransactionValue(detail.stage)}</p><p className="mt-2 text-sm text-cyan-100">{detail.propertyDisplay}</p>{detail.clientCase && <Link href={`/agent/clients/${detail.clientCase.id}`} className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-cyan-100 hover:text-white">{detail.clientCase.displayName}<ChevronRight size={15} /></Link>}</header>
      <section className="mt-6 grid gap-5 lg:grid-cols-2"><section className="border border-white/10 p-5"><h2 className="text-lg font-semibold text-white">Case parties</h2><ul className="mt-4 space-y-3">{detail.parties.map((party) => <li key={party.id} className="text-sm text-slate-300"><p className="font-medium text-white">{party.displayLabelSnapshot}</p><p className="text-slate-400">{humanizeTransactionValue(party.role)}</p></li>)}</ul></section><section className="border border-white/10 p-5"><h2 className="text-lg font-semibold text-white">Recordkeeping boundary</h2><p className="mt-3 text-sm leading-6 text-slate-300">This is an internal operational record. It is not a Compass office file, document repository, or output-delivery workflow.</p><p className="mt-3 flex items-center gap-2 text-xs text-cyan-100"><ShieldCheck size={14} />No document storage or external action is active.</p></section></section>
      <section className="mt-6 border border-white/10 p-5"><h2 className="flex items-center gap-2 text-lg font-semibold text-white"><History size={18} />History</h2><div className="mt-4 space-y-3">{detail.timelineEvents.map((event) => <div className="border-l border-cyan-100/35 pl-4" key={event.id}><p className="text-sm font-medium text-white">{eventLabel(event.eventType)}</p><p className="mt-1 text-xs text-slate-400">Recorded {dateTime(event.recordedAt)}</p></div>)}</div></section>
      <section className="mt-6 grid gap-5 lg:grid-cols-3"><section className="border border-white/10 p-5"><h2 className="text-sm font-semibold text-white">Update status</h2><select value={nextStatus} onChange={(event) => setNextStatus(event.target.value)} className="mt-3 min-h-10 w-full border border-white/15 bg-[#071014] px-3 text-sm text-white"><option value="">Select status</option>{detail.status === 'DRAFT' && <option value="ACTIVE">Active</option>}{['DRAFT', 'ACTIVE'].includes(detail.status) && <option value="CANCELLED">Cancelled</option>}{detail.status === 'ACTIVE' && <option value="CLOSED">Closed</option>}</select><button disabled={busy || !nextStatus} onClick={() => void mutate('UPDATE_STATUS', { status: nextStatus })} className="atlas-action atlas-action-secondary mt-3">Update status</button></section><section className="border border-white/10 p-5"><h2 className="text-sm font-semibold text-white">Advance stage</h2><select value={nextStage} onChange={(event) => setNextStage(event.target.value)} className="mt-3 min-h-10 w-full border border-white/15 bg-[#071014] px-3 text-sm text-white"><option value="">Select stage</option>{['UNDER_CONTRACT','INSPECTION_PERIOD','TITLE_DUE_DILIGENCE','APPRAISAL_FINANCING','PRE_CLOSING','OTHER_REVIEW_REQUIRED'].map((stage) => <option key={stage} value={stage}>{humanizeTransactionValue(stage)}</option>)}</select><button disabled={busy || !nextStage || detail.status !== 'ACTIVE'} onClick={() => void mutate('ADVANCE_STAGE', { stage: nextStage })} className="atlas-action atlas-action-secondary mt-3">Advance stage</button></section><section className="border border-white/10 p-5"><h2 className="flex items-center gap-2 text-sm font-semibold text-white"><CalendarClock size={16} />Associate property</h2><input value={propertyId} onChange={(event) => setPropertyId(event.target.value)} disabled={Boolean(detail.canonicalPropertyId) || detail.stage !== 'PREPARATION'} placeholder="Case property ID" className="mt-3 min-h-10 w-full border border-white/15 bg-transparent px-3 text-sm text-white disabled:opacity-50" /><button disabled={busy || !propertyId || Boolean(detail.canonicalPropertyId) || detail.stage !== 'PREPARATION'} onClick={() => void mutate('ASSOCIATE_PROPERTY', { canonicalPropertyId: propertyId })} className="atlas-action atlas-action-secondary mt-3">Associate property</button></section></section>
    </>}
  </div></main>;
}
